[[INSTALL_WIN]]
=== Windows

- Download _WSJT_ from the {homepage}. Click on _WSJT_ at the left
margin and then on the desired download link.

- Execute the downloaded file and follow its installation 
instructions.

- Install _WSJT_ into its own directory rather than the conventional
location +C:\Program Files\WSJT10+.  The suggested default directory is
+C:\WSJT10+.

- All files relating to _WSJT_ will be stored in the chosen
installation directory and its subdirectories. You can uninstall
_WSJT_ by removing the installation directory and its contents.

- The built-in Windows facility for time synchronization is usually
not adequate.  We recommend Meinberg NTP: see {ntpsetup} for
downloading and installation instructions.  

CAUTION: If you are using a sound card that is also the Windows
default audio device, be sure to turn off all Windows sounds so they
are not transmitted over the air.


[[INSTALL_UBU]]
=== Linux
As with OSX, this section refers to the latest code in the repository. As of
this writing, version 10.0

The biggest issue with compiling _WSJT_ on Linux seems to be with
Python3-Numpy. Some Linux distributions include Python-Numpy (built with 
Python 2.x.x) with their desktop packaging. If your desktop includes
Python-Numpy built with Python 2.x.x, use the command 
*kbd:[./autogen.sh --with-f2py=(/path/to/f2py3)]* to pass the correct location
for F2PY.

* To properly build _WSJT v10.0_, you you must have all the core development
packages installed. See <<SRC_CODE,Dev Package List>> below for details.+
 :: svn co https://svn.code.sf.net/p/wsjt/wsjt/trunk wsjt-code +
 :: cd ./wsjt-code +
 :: ./autogen.sh +
 :: make +
 :: sudo make install +

* To list autotools enabled options, use: +
 :: ./autogen.sh +
 :: ./configure --help=short +


By default, due to potential conflicts with _WSJT-X_, the source installation
will be located in pass:[/usr/local/wsjt]. It is highly advised to keep this prefix
location as is. If you must change the pass:[--prefix], consider using pass:[/opt]
rather than pass:[/usr/local].

For running _WSJT_ after installation, if you followed the example above,
use the following help command

[source,shell]
----------
/usr/local/wsjt/bin/wsjt -h
----------

[[INSTALL_OSX]]
=== OS X

This guide refers to installation of _WSJT_ on Mac OSX 10.7 and 10.9.  This
scheme should also work on OSX 10.8 but has not been tested.  There are
problems with Tcl/Tk libraries which prevent the code from running on OSX 10.10.
You will need to be familiar with Unix commands in a Terminal window.

- Install the latest version of Xcode, available free from developer.apple.com.
Launch Xcode and visit Preferences -> Downloads and select "command line tools" 
and install them.

- You will need a Fortran compiler.  Visit  https://gcc.gnu.org/wiki/GFortranBinaries#MacOS
and select an installer for your OSX version.

- The default Python installed on a Mac is version 2.7.   A later version is required.  Visit
https://www.python.org/downloads/release/python-342/ and select _Mac OS X 64-bit/32-bit installer_.  Download the package 
and install.

- For the next downloads I recommend that you create an installation directory and use this
for the downloads that follow.  

- You need the _numpy_ suite.   Visit http://sourceforge.net/projects/numpy/files/NumPy/1.9.1/ and download _numpy-1.9.1.tar.gz_.   
Expand this file and type: +
 :: python setup.py build --fcompiler=gnu95 +
 :: sudo python setup.py install +

- Install portaudio.  Visit  http://www.portaudio.com/download.html and download _pa_snapshot.tgz_.  Expand this file
and type: +
 :: configure +
 :: make +
 :: sudo make install +

- Install libsamplerate.  Visit  http://www.mega-nerd.com/SRC/download.html and download _libsamplerate-0.1.8.tar.gz_.  Expand this file and type: +
 :: configure +
 :: make +
 :: sudo make install +

- Install Fast Fourier code.  Visit http://www.fftw.org/download.html and download _fftw_3.3.4.tar.gz_ and expand the file. Type: +
 :: configure --enable-float +
 :: make +
 :: sudo make install +

- Install PIL for imaging.  Type: +
 ::  sudo pip install Pillow +

- Now it is time to download the source code.  Type the following which will download the complete source tree
and install in a new directory _wsjt_.   
 :: svn co svn://svn.code.sf.net/p/wsjt/wsjt/trunk wsjt +

- Finally, change your working directory to _wsjt_ and type: +
 :: configure --with-portaudio-include-dir=/usr/local/include --with-portaudio-lib-dir=/usr/local/lib +
 :: make +
 :: python wsjt.py +

and if all has proceeded without error, _WSJT_ should launch.

You will need a Mac driver to control the serial link between your Mac and the transmitter.

[[SRC_CODE]]
=== Source Code

Source code is available from the public repository at {devsvn}. To
compile the program you will need to install the following packages:

[[CORE-DEV-PKGS]]
.Core Development Packages
[cols="1,1", options="header, autowidth"]
|===
|Package|Description

|Autoconf
|GNU automatic configure script builder

|GCC
|GNU C Compiler

|Make
|GNU utility for Directing compilation

|Subversion
|Advanced version control system

|Python3
|Interactive high-level object-oriented language, v3.2 or above

|Python3 Numpy
|Fast array facility to the Python 3 language

|Python3 Tk
|Tkinter - Writing Tk applications with Python 3.x

|Python3 PIL
|Python Imaging Library (Python3)

|Python3 PIL Image Tk
|Python Imaging Library - ImageTk Module (Python3)

|Python3 Dev
|Header files and a static library for Python3

|Samplerate Dev
|Development files for audio sample rate conversion

|FFTW3 Dev
|Library for computing Fast Fourier Transforms

|Portaudio 19 Dev
|Portable audio I/O - development files

|MinGW-32
|Cross Compiling tool chain (*Windows Only)
|===

If you want to compile documentation, in addition to the <<CORE-DEV-PKGS,Core
Development Packages>>, you will need the following packages:

[NOTE]
=====
You can disable building documentation, thus alleviate 
<<DOC-PKGS,Documentation Package Requirements>> by using the build option
*kbd:[./autogen.sh --disable-docs]*
=====

[[DOC-PKGS]]
.Documentation Package Requirements
[cols="1,1", options="header, autowidth"]
|===
|Package|Description

|Ruby
|Interpreter of object-oriented scripting

|Asciidoctor
|AsciiDoc to HTML rendering for Ruby
|===

If you want to compile documentation, in addition to the <<CORE-DEV-PKGS,Core
Development Packages>>, you will need the following packages:

[NOTE]
=====
You can disable building Manpages, thus alleviate a large number of 
<<DOC-PKGS,Manpage Package Requirements>> by using the build option
*kbd:[./autogen.sh --disable-manpages]*
=====

[[MANP-PKGS]]
.Manpage Package Requirements ( *Nix Only )
[cols="1,1", options="header, autowidth"]
|===
|Package|Description

|AsciiDoc
|Highly configurable text format for writing documentation

|Python2
|Interactive high-level object-oriented language
|===

