#!/user/bin/env bash

#
# Part of the JTSDK-NIX Project
# Build Python3 Numpy-1.8.1 from source
# pre-req: LAPACK and ATLAS

#------------------------------numpy build-------------------------------------#

function build_numpy() {

set -e

_PKG_NAME=numpy
_FILE=numpy-1.8.1.tar.gz
_URL="http://softlayer-dal.dl.sourceforge.net/project/numpy/NumPy/1.8.1/numpy-1.8.1.tar.gz"
_MD5A="be95babe263bfa3428363d6db5b64678"
_INSTALL_MKR=$_MKRD/$_PKG_NAME/$_PKG_NAME-install.mkr

# test python3 version
cd "$_SRCD"
_PYV=$(python3 -V |awk '{print $2}')
if [[ $_PYV > "3.3.0" ]];then
	echo ".. Python Version is .. OK"
else
	echo "Python3 => 3.3.0 was Not Found"
	echo "Please ensure you have have Python verson 3.3.0 or"
	echo "later installed on your system before continuing"
	break
	clean_exit
fi

# Download Numpy-1.8.1
echo ".. downloiading $_FILE from Sourceforge"
cd $_SRCD
wget -q -r --tries=5 $_URL -O $_SRCD/$_FILE

# unpack and install Numpy
echo ".. unpacking $_FILE"
cd $_SRCD
tar -xzvf $_FILE
cd $_SRCD/numpy-1.8.1

# Run MD5SUM
if [[ -f $_SRCD/$_FILE ]]; then
	_MD5B=$(md5sum $_SRCD/$_FILE |awk '{print $1}')
	echo ".. MD5A Checksum is: "$_MD5A
	echo ".. MD5B Checksum is: "$_MD5B
else
	clear
	echo
	echo "The Automated $_FILE Download .. FAILED"
	echo "In order to continue, you need to manually download"
	echo "$_FILE before continuing."
	echo
	echo "For Details, see $_LOGS/setup.log"
	echo
	echo "Actoiins to Take:"
	echo " [1] Download Numpy:" $_URL
	echo " [2] Save to: $_SRCD"
	echo " [3] Re-Run setup.sh"
	echo
	echo "Setup will now exit."
	echo
	read -p "Press [Enter] to continue ..."
	clean_exit
fi

if [[ $_MD5B = $_MD5A ]]; then
	_MD5C=OK
echo ".. MD5SUM is ..." $_MD5C
	sleep 2
else
	echo "MD5A" $_MD5A
	echo "MD5B" $MD5B
	echo "Do No Match"
	echo "For Details, see $_LOG"
	echo
	echo "Actions To Take:"
	echo " [1] Download Numpy:" $_URL
	echo " [2] Save to: $_SRCD"
	echo " [3] Re-Run setup.sh"
	echo
	echo "Setup will now exit."
	echo
	read -p "Press [Enter] to continue ..."
	clean_exit
fi

# we need sudo here to install system wide:
# This can take a while, and is the highest potentical failure point.
#
echo ".. building $_PKG_NAME first, then installing"
mkdir -p $_MKRD/$_PKG_NAME
cd $_SRCD/numpy-1.8.1

# build first
echo ".. starting the build"
python3 setup.py build --fcompiler=gnu95

# install the build
sudo python3 setup.py install --record $_INSTALL_MKR
wc -l < $_MKRD/$_PKG_NAME/$_PKG_NAME-install.mkr |awk '{print $1}' > $_FILE_COUNT_MKR

# change ownership to $USER after install
echo ".. changing ownership of Folders and File to $USER"
cd ..
sudo chown -R $USER:$USER $_SRCD/numpy-1.8.1
sudo chown $USER:$USER $_MKRD/$_PKG_NAME/$_PKG_NAME-install.mkr

# reset sudo to ask for user PW if needed again
echo ".. changing back to normal user"
sudo -k

# verify Numpy instlled correctly
echo ".. verifying Numpy install"
pip3 list | tee -a > $_MKRD/$_PKG_NAME/pip3-list.mkr 2>&1
_NUMP=$(grep ^numpy < $_MKRD/$_PKG_NAME/pip3-list.mkr |awk '{print $1}')

if [[ $_NUMP = "numpy" ]];then
	echo "Numpy Installation Complete"
	rm $_MKRD/$_PKG_NAME/pip3-list.mkr
else
	echo
	echo "Numpy Installation Error"
	echo "There appears to have been an Numpy install problem."
	echo "Please check the build log for details:"
	echo
	echo "Location: $_LOGS/$_PKG_NAME-setup.log"
	echo 
	read -p "Press [Enter] to continue ..."
	clean_exit
fi
}
