[[INSTALL_WIN]]
=== Windows

- Download _WSPR_ from the {homepage}. Click on _WSPR_ at the left
margin and then on the desired download link.

- Execute the downloaded file and follow its installation 
instructions.

- Install _WSPR_ into its own directory rather than the conventional
location +C:\Program Files\WSPR+.  The suggested default directory is
+C:\WSPR+.

- All files relating to _WSPR_ will be stored in the chosen
installation directory and its subdirectories. You can uninstall
_WSPR_ by removing the installation directory and its contents.

- The built-in Windows facility for time synchronization is usually
not adequate.  We recommend Meinberg NTP: see {ntpsetup} for
downloading and installation instructions.  

CAUTION: If you are using a sound card that is also the Windows
default audio device, be sure to turn off all Windows sounds so they
are not transmitted over the air.

[[INSTALL_OSX]]
=== OS X

NH6Z has made a binary available for download. Download and follow his
instructions {nh6z}. 

[[INSTALL_UBU]]
=== Linux

For Ubuntu and other recent 32/64 bit Debian-based systems, you can download
an installation file from another link on the {wspr}. To install and execute
_WSPR_, put the downloaded file in your home directory and execute the following
commands from a command-prompt window, if necessary substituting the correct
revision number for the one shown:

 $ sudo dpkg --instdir=. -i wspr_3.00r2319_i386.deb 
 $ cd WSPR 
 $ ./wspr 

[[INSTALL_SOURCE]]
=== Source Code

Building _{prog}_ from source code is straightforward but takes time
and requires some experience.  Source code can be downloaded from
{wspr_svn}, the public repository at {devsvn}. Detailed instructions
are available in the {dev_guide}.  You will need the following
development tools:

* Subversion
* gcc or equivalent C compiler
* gfortran
* fftw3 (headers and libraries)
* portaudio19-dev (headers and libraries)
* samplerate (headers and libraries)
* python3, python3-dev, python3-numpy, python3-pil or pillow, python3-tk
python3-imaging-tk, autoconf, autotools-dev
* hamlib utilities

