
The following are general instructions for compiling _{prog}_ from source
code. For detailed instructions, see {dev_guide}.

_{prog}_ source code is available {wspr_svn}, the public repository at
{devsvn}. To compile the program you will need to install the following packages:

TIP: Package names very considerably between the various Linux / Mac / BSD
adn Windows versions, consult your distrobution package manager for the
appropriate packages.

* Subversion
* C/C{plus}{plus} Compiler
* gfortran
* fftw3 (headers and libraries)
* portaudio19-dev (Headers and Libraries)
* samplerate (Headers and Libraries)
* python3, python3-dev, python3-numpy, python3-pil or pillow, python3-tk
python3-imaging-tk, autoconf, autotools-dev
* hamlib utils

.*Nix / Mac OSX
* Open a command ternaim (X-Term) and issue the following commands:
-----
svn co http://svn.code.sf.net/p/wsjt/wsjt/branches/wspr
-----

* At the prompt, type:
-----
./autogen.sh
make
sudo or root make install
-----

* {prog} will be installed to: /home/$USER/.wspr

.Run _{prog}_
* To run, just type: wspr



