[[INSTALL_WIN]]
=== Windows

- Download _WSJT_ from the {homepage}. Click on _WSJT_ at the left
margin and then on the desired download link.

- Execute the downloaded file and follow its installation 
instructions.

- Install _WSJT_ into its own directory rather than the conventional
location +C:\Program Files\WSJT10+.  The suggested default directory is
+C:\WSJT10+.

- All files relating to _WSJT_ will be stored in the chosen
installation directory and its subdirectories. You can uninstall
_WSJT_ by removing the installation directory and its contents.

- The built-in Windows facility for time synchronization is usually
not adequate.  We recommend Meinberg NTP: see {ntpsetup} for
downloading and installation instructions.  

CAUTION: If you are using a sound card that is also the Windows
default audio device, be sure to turn off all Windows sounds so they
are not transmitted over the air.


[[INSTALL_UBU]]
=== Linux

Still to come ...

[[INSTALL_OSX]]
=== OS X

Still to come ...

[[SRC_CODE]]
=== Source Code

Source code is available from the public repository at {devsvn}. To
compile the program you will need to install the following packages:

- Subversion
- Python 3.x, and the following Python packages
** python-numpy
** python-imaging-tk
** python-pmw
- gcc
- gfortran or g95
- fftw3
- PortAudio
- libsamplerate
- MinGW (for Windows only)

With Subversion installed, the full source code for _WSJT_ can be
downloaded with the command:

  svn co svn://svn.berlios.de/wsjt/trunk

// Need further compiling Instructions
For some basic instructions on building _WSJT_ from source code, see the
section <<COMPILING,Compiling WSJT-X>> near the end of this Guide.
