=== JTMS

JTMS uses Minimum Shift Keying (MSK) at 11025 / 8 = 1378.125 baud.
Messages are free-form and have lengths 5,7,9,11,13,17,19,23 or 29
characters, padded when required with one or more trailing blanks.
Characters are mapped to numerical values in the range 0 to 63
according to position in the first line below.  (The second and third
lines may be used to read off an index value: for example, B has the
value 11 and ? is 38.)

----
  0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ./?-
            1         2         3         4
  01234567890123456789012345678901234567890
----

The 6-bit binary representation for each character value is augmented
with an even parity bit. The resulting 7-bit sequences are sent using
audio frequency 1155.47 Hz to represent 0 and 1855.53 Hz to represent
1.  A message is transmitted repeatedly for a full transmission,
maintaining phase continuity at all transitions between tones.

Four single-tone messages are defined in JTMS: R26, R27, RRR and 73.
They are transmitted as pure tones of 882, 1323 and 1764, and 2205 Hz
respectively.  Pings from these transmissions are easily recognized by
the human ear, easily seen on spectrum displays, and readily detected
by appropriate software.

=== FSK441

FSK441 uses four-tone frequency shift keying at 441 baud.  The
frequencies of the audio tones are 882, 1323, 1764, and 2205 Hz.  Each
encoded character uses three tone intervals and therefore requires
3/441 seconds (approximately 2.3 ms) for transmission.  FSK441
accommodates an alphabet of 43 characters, as listed in the table
below:

-------------------------------
       1      001          H   120 
       2      002          I   121 
       3      003          J   122 
       4      010          K   123 
       5      011          L   130 
       6      012          M   131 
       7      013          N   132 
       8      020          O   133 
       9      021          P   200 
       .      022          Q   201 
       ,      023          R   202 
       ?      030          S   203 
       /      031          T   210 
       #      032          U   211 
     <space>  033          V   212 
       $      100          W   213 
       A      101          X   220 
       B      102          Y   221 
       C      103          0   223 
       D      110          E   230 
       F      112          Z   231 
       G      113 
-------------------------------

In the table the four tones are labeled 0-3, representing the tones
882, 1323, 1764, and 2205 Hz.  For example, the letter T has the code
210 and is transmitted by sending sequentially the tones at 1764,
1323, and 882 Hz. Note that the character <space> is encoded as 033,
and that tone sequences starting with the highest tone (number 3) are
not used.  It follows that if transmitted messages always include at
least one space, a decoding algorithm can establish proper
synchronization from the message content itself, with zero overhead.
This encoding strategy is one of the secrets of the high efficiency of
FSK441 for meteor scatter communications.

The four possible single-tone character codes, namely 000, 111, 222,
and 333, are reserved for special use as shorthand messages. When sent
repeatedly, these reserved characters generate pure single-frequency
carriers.  Their pings are easily recognized by the human ear and also
by appropriate software.  The shorthand messages are defined to mean
R26, R27, RRR, and 73, respectively.  These messages are frequently
used in meteor scatter QSOs, after callsigns have been exchanged.
They are not used in IARU Region 1, where activity levels are high
enough that messages should always be accompanied by callsigns.

=== ISCAT

ISCAT messages are free-form, up to 28 characters in length.
Modulation is 42-tone frequency-shift keying at 11025 / 512 = 21.533
baud (ISCAT-A), or 11025 / 256 = 43.066 baud (ISCAT-B).  Tone
frequencies are spaced by an amount equal to the baud rate.  The
available character set is

----
 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ /.?@-
----

Transmissions consist of sequences of 24 symbols: a ``sync'' pattern
of four symbols at tone numbers 0, 1, 3, and 2, followed by two
symbols with tone number corresponding to the message length, and
finally 18 symbols conveying the user's message, sent repeatedly
character by character.  The message always starts with +@+, the
beginning-of-message symbol.  The sync pattern and message-length
indicator have a fixed repetition period, recurring every 24 symbols.
Message information occurs periodically within the 18 symbol positions
set aside for its use, repeating at its own natural length.

For example, consider the user message +CQ WA9XYZ+.  Including the
beginning-of-message symbol +@+, the message is 10 characters long.
Using the character sequence displayed above to indicate tone numbers,
the transmitted message will therefore start out as shown in the first
line below:

----
 0132AA@CQ WA9XYZ@CQ WA9X0132AAYZ@CQ WA9XYZ@CQ W0132AAA9X ...
 sync##                  sync##                 sync##
----

Note that the first six symbols (four for sync, two for message
length) repeat every 24 symbols.  Within the 18 information-carrying
symbols in each 24, the user message +@CQ WA9XYZ+ repeats at its own
natural length, 10 characters.  The resulting sequence is extended as
many times as will fit into a Tx sequence.

=== JT6M

JT6M uses 44-tone FSK with a synchronizing tone and 43 possible data
tones -- one for each character in the supported alphanumeric set, the
same set used for FSK441. The sync tone is at frequency 
100 x 11025 / 1024 = 1076.66 Hz, and the 43 other possible tones are
spaced at intervals of 11025 / 512 = 21.53 HZ up to 2002.59 Hz.
Transmitted symbols are keyed at a rate of 21.53 baud, so each one
lasts for 1/21.53 = 0.04644 seconds. Every third symbol is the sync
tone.The transmission rate of user data is therefore 21.53 x (2/3) = 14.4
characters per second.


.Parameters of WSJT Fast Modes
[width="90%",cols="h,9*",frame="topbot",options="header"]
|============================================================================
|Mode   |T/R (s)| Mod   |  FEC    |Nsps| Baud |df (Hz)|BW (Hz)| cps |S/N (dB)
|JTMS   | 15,30 | MSK   | parity  | 8  | 1378 | 689 | 2067 | 197 | -1
|FSK441 | 15,30 | 4-FSK |         | 25 | 441  | 441 | 1764 | 147 | -1
|ISCAT-A| 15,30 | 42-FSK|         |512 | 21.5 | 21.5| 905  | 16.5| -17
|ISCAT-B| 15,30 | 42-FSK|         |256 | 43.1 | 43.1|1809  | 32.3| -17
|JT6M   | 15,30 | 44-FSK|         |512 | 21.5 | 21.5| 947  | 14.4| -10
|============================================================================

=== JT65

A detailed description of the JT65 protocol was published in
{jt65protocol} for September-October 2005.  Briefly stated, JT65 uses
60 s T/R sequences and carefully structured messages.  Standard
messages are compressed so that two callsigns and a grid locator can
be transmitted with just 71 bits.  A 72nd bit serves as a flag to
indicate that the message consists of arbitrary text (up to 13
characters).  Special formats allow other information such as add-on
callsign prefixes or numerical signal reports to be substituted for
the grid locator.  The aim of source encoding is to compress the
common messages used for weak-signal QSOs into a minimum fixed number
of bits.  After compression, a Reed Solomon (63,12) error-correcting
code converts 72-bit user messages into sequences of 63 six-bit
channel symbols.

JT65 requires tight synchronization of time and frequency between
transmitter and receiver.  Each transmission is divided into 126
contiguous time intervals or symbols, each of length 4096/11025 =
0.372 s. Within each interval the waveform is a constant-amplitude
sinusoid at one of 65 pre-defined frequencies, and frequency changes
between intervals are accomplished in a phase-continuous manner.  Half
of the channel symbols are devoted to a pseudo-random synchronizing
vector interleaved with the encoded information symbols.  The sync
vector allows calibration of relative time and frequency offsets
between transmitter and receiver.  A transmission nominally begins at
t = 1 s after the start of a UTC minute and finishes at t = 47.8 s.
The synchronizing tone is at 11025 x 472 / 4096 = 1270.5 Hz, and is
normally sent in each interval having a 1 in the following
pseudo-random sequence:

 100110001111110101000101100100011100111101101111000110101011001
 101010100100000011000000011010010110101010011001001000011111111

Encoded user information is transmitted during the 63 intervals _not_
used for the sync tone. Each channel symbol generates a tone at
frequency 1275.8 + 2.6917 Nm Hz, where N is the value (0 - 63) of the
six-bit symbol, and m is 1, 2, or 4 for JT65 sub-modes A, B, or C.
The signal report OOO is conveyed by reversing sync and data positions
in the transmitted sequence.  Shorthand messages dispense with the
sync vector and use intervals of 1.486 s (16,384 samples) for the
alternating tones.  The lower frequency is always 1270.5 Hz, the same
as that of the sync tone, and the frequency separation is 26.92 nm Hz
with n = 2, 3, 4 for the messages RO, RRR, and 73.

=== JT4

JT4 uses 72-bit structured messages nearly identical to those in
JT65. Error control coding (ECC) uses a strong convolutional code with
constraint length K=32, rate r=1/2, and a zero tail, leading to an
encoded message length of (72+31) x 2 = 206 information-carrying
bits. Modulation is 4-tone frequency-shift keying at 11025 / 2520 =
4.375 baud.  The frequency spacing between tones and total bandwidth
depends on the submode.


[[SLOW_TAB]]
.Parameters of WSJT Slow Modes
[width="90%",cols="h,9*",frame="topbot",options="header"]
|============================================================================
|Mode  |T/R (s)|Mod   |  FEC     |Nsps| Baud |df (Hz)|BW (Hz)| cps |S/N (dB)
|JT65A |  60   |65-FSK|RS(63,12) |4096| 2.69 | 2.69| 178  | 46.8| -25
|JT65B |  60   |65-FSK|RS(63,12) |4096| 2.69 | 5.38| 355  | 46.8| -24
|JT65C |  60   |65-FSK|RS(63,12) |4096| 2.69 |10.77| 711  | 46.8| -23
|JT65B2|  30   |65-FSK|RS(63,12) |4096| 2.69 | 5.38| 355  | 46.8| -22
|JT65C2|  30   |65-FSK|RS(63,12) |4096| 2.69 |10.77| 711  | 46.8| -21
|JT4A  |  60   |4-FSK |K=32,r=1/2|2520| 4.375|4.375| 17.5 | 47.1| -23
|JT4B  |  60   |4-FSK |K=32,r=1/2|2520| 4.375|8.75 | 35   | 47.1| -22
|JT4C  |  60   |4-FSK |K=32,r=1/2|2520| 4.375|17.5 | 70   | 47.1| -21
|JT4D  |  60   |4-FSK |K=32,r=1/2|2520| 4.375|39.4 | 158  | 47.1| -20
|JT4E  |  60   |4-FSK |K=32,r=1/2|2520| 4.375|78.8 | 315  | 47.1| -19
|JT4F  |  60   |4-FSK |K=32,r=1/2|2520| 4.375| 158 | 630  | 47.1| -18
|JT4G  |  60   |4-FSK |K=32,r=1/2|2520| 4.375| 315 |1260  | 47.1| -17
|============================================================================
