[qanda]
I am running WSJT-X under Windows and using the integrated logging facility.  Where has the system put my log file?::

Logs and other writeable files will be found in the directory 
+
-----
 %APPDATA%\..\Local\WSJT-X
-----

Why does the *Flatten* feature cause my displayed spectrum to curve steeply upward near the edges, before falling where the IF filter cuts off?::


_WSJT-X_ does not expect a steep filter edge within the displayed
passband, except perhaps a low-frequency cutoff below 200 Hz. Either
use a wider IF filter or reduce the displayed passband by decreasing
*Bins/Pixel*, increasing *Start*, or reducing the width of the *Wide
Graph*.  You might also choose to re-center the filter passband, if
such control is available.

Occasionally, _WSJT-X_ unexpectedly quits. I have read this is because I set *Polling interval* to a nonzero value. How can I fix this issue?::

A few radios do not interact properly with the +hamlib+ library calls
used in _WSJT-X_.  We are working to resolve this and other
CAT-control issues.  In the meantime you can run with *Polling
interval* set to 0, or control your radio through _DX Labs Commander_
or _Ham Radio Deluxe_.

How should I configure _WSJT-X_ to run multiple instances?::

Each instance must be executed from a separate directory.  Be sure to
check *Advanced | Allow multiple instances* in the *Setup* menu for
each one; then exit and restart the program.  This step needs be done
just once.

_WSJT-X_ does not set my VFO (A or B, if available) to USB on any band I select. Why is that?::

Automatic setting of mode for a selected band depends on your radio
manufacturer's implementation of CAT control.  The details are not
standardized between manufacturers, or even between rigs from a given
manufacturer, so this feature is difficult to implement. _WSJT-X_ does
not currently support setting USB mode. Set your VFO(s) to USB for all
bands you intend to work before launching _WSJT-X_, as suggested in
<<TUT_XCVR,Transceiver Setup>>, above.

How do I know what settings to use for rig control (CAT) and PTT?::

Your radio’s manual will have these settings in a section for computer
setup, digital modes and TNC interface specifications. These may also
be detailed in a programmers guide which is usually offered as a
downloadable file from the manufacturer's web site.  Do a web search
for something like ``rig cat for _your_rig_model_'' which should give
you several places to look.
+
If your rig uses CAT control and PTT control on separate cables, the
port settings could very easily be different for each cable. You may
find more than one settings configuration that works correctly. Some
experimentation is likely to be necessary.

How does _WSJT-X_ use both VFOs when operating in split mode?::

Let's assume that *Split* mode is set on _WSJT-X_ and the rig.  We also
assume that *{plus}2 kHz* is not set and that your receiver's bandwidth
is at least 4000 Hz.
+
Using the 20 m band as an example, let's observe the waterfall window
while looking for contacts. VFO-A, the receiving VFO, will be set to
14.076 MHz, the nominal calling frequency for JT65.  When
transmitting, _WSJT-X_ will always generate an audio signal in the
range 1500 - 2000 Hz.  Put the red Tx waterfall cursor at 1700 Hz.
You should see VFO-B, the Tx VFO, also set to 14.0760 MHz. That's
because 1700 Hz lies within the 1500 - 2000 Hz range, so no adjustment
to the transmit frequency is required.  Our Tx signal will be at
14.076 MHz {plus} 1700 Hz, or 14.077700 MHz, and this frequency will
be shown in the _WSJT-X_ log if we log a QSO at these settings.
+
Now move the Tx cursor to 2200 Hz.  _WSJT-X_ still wants to generate
audio in the 1500 - 2000 Hz range, so the VFO-B frequency is increased
to 14.0765 MHz. The transmitted frequency will be 14.0765 MHz {plus}
1700 Hz, or 14.07820 MHz.
+
Similarly, if the Tx cursor is set below the 1500 - 2000 Hz range,
VFO-B must be set lower than 14.076 to keep the transmitted audio in
the desired 1500 - 2000 Hz range.

My rig has only a single SSB filter, about 2700 Hz bandwidth.  Can I use split mode?::

Set the radio to *Split* mode and _WSJT-X_ to *Split Tx*.  To operate
primarily in the JT9 frequency range, check the *{plus}2 kHz*
box. VFO-A will then be moved up to 14.078 MHz.  The JT9 subband now
falls between about 500 Hz and 2000Hz on the waterfall display.  As
described above, VFO-B will be adjusted so as to keep your Tx audio
always between 1500 and 2000 Hz.  To operate JT65, simply uncheck the
*{plus}2 kHz* option.

