[qanda]
I am running WSJT-X under Windows and using the integrated logging facility.  Where has the system put my log file?::

Logs and other writeable files will normally be found in the directory 
+
-----
 C:\Users\username\AppData\Local\WSJT-X
-----

Why does the *Flatten* feature cause my displayed spectrum to curve steeply upward near the edges, before falling where the IF filter cuts off?::

_WSJT-X_ does not expect a steep filter edge within the displayed
passband, except perhaps a low-frequency cutoff below 200 Hz. Either
use a wider IF filter or reduce the displayed passband by decreasing
*Bins/Pixel*, increasing *Start*, or reducing the width of the *Wide
Graph*.  You might also choose to re-center the filter passband, if
such control is available.


My rig has only a single SSB filter, about 2700 Hz bandwidth.  Can I use split mode?::

Set the radio to *Split* mode and _Split Operation_ to *Rig* (or if
necessary, *Fake It*) on the *Settings | Radio* tab.  To operate
primarily in the JT9 frequency range, check the *{plus}2 kHz*
box. VFO-A will then be moved up to 14.078 MHz.  The JT9 subband now
falls between about 500 Hz and 2000Hz on the waterfall display.  As
described above, VFO-B will be adjusted so as to keep your Tx audio
always between 1500 and 2000 Hz.  To operate JT65, simply uncheck the
*{plus}2 kHz* option.

