# JTSDK QT5 Tool-Chain File
# Part of the JTSDK v2.0.0 Project
SET (CMAKE_SYSTEM_NAME Windows)
SET (BASED C:/JTSDK)
SET (QTDIR C:/JTSDK/qt5/5.2.1/mingw48_32)
SET (HAMLIB C:/JTSDK/hamlib)
SET (FFTW C:/JTSDK/fftw3f)
SET (CMAKE_PREFIX_PATH ${QTDIR} ${FFTW} ${HAMLIB} ${HAMLIB}/bin)
SET (CMAKE_FIND_ROOT_PATH ${BASED})
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)