# JTSDK-QT Tool-Chain File
# Part of the JTSDK v2.0.0 Project
# NOTE: WSKT-X uses Hamlib3, not Hamlib2
SET (CMAKE_SYSTEM_NAME Windows)
SET (BASED C:/JTSDK)
SET (QTDIR C:/JTSDK/qt5)
SET (HAMLIB C:/JTSDK/hamlib3)
SET (FFTW C:/JTSDK/fftw3f)
SET (CMAKE_PREFIX_PATH ${QTDIR} ${FFTW} ${HAMLIB} ${HAMLIB}/bin)
SET (CMAKE_FIND_ROOT_PATH ${BASED})
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
