// Status=review
= Developer's Guide to WSJT and Related Programs
//:Author: Joe Taylor, K1JT
//:Date: {localdate}
:badges:
:icons:
:numbered:
:keywords: amateur radio weak signal communication K1JT WSJT FSK441 JT65 JT6M JT9 WSJTX
:description: Software for Amateur Radio Weak-Signal Communication

// use global link file
include::../../global/links.adoc[]

== Overview

The WSJT family of programs for weak-signal amateur radio
communication includes _WSJT_, _WSPR_, _MAP65_, _WSJT-X_, and
_WSPR-X_.  User interfaces for _WSJT_ and _WSPR_ are written in
Python, and build procedures for them are similar.  User interfaces
for _MAP65_, _WSJT-X_, and _WSPR-X_ are written in C++ and use the Qt
framework.  Most number-crunching in the WSJT programs is done in
Fortran.

This Developer's Guide is a work in progress.  We currently provide
instructions for compiling _WSJT-X_ in Linux and we outline the
prerequisites for compiling it in Windows.  Similar procedures can be
used for _MAP65_ and _WSPR-X_.  Instructions for the Python-based
programs are yet to come.

Please send feedback on this Guide to {greg_beam}.

== Source Code

All source code for the WSJT programs is available at the open-source
repository known as {berlios1}, under control of the version-control
program {svn}.  You can install Subversion in Windows from the above
link; in Linux use

[source,bash]
-----
sudo apt-get install subversion 
-----
or an equivalent command for your Linux distribution.  

You can browse the organization of files in the repository {wsjt_svn}.
Code for program _WSJT_ lies in the +trunk+ directory, while code for
the other programs is found in +.../branches/map65+,
+.../branches/wsjtx+, and +.../branches/wsprx+.  Various experimental
branches may also exist, and snapshots of code for certain released
program versions may be obtained from the +.../tags+ directory.

You can do an anonymous checkout of source code for a specific program
with a command of the following form:

[source,bash]
-----
svn co svn://svn.berlios.de/wsjt/branches/wsjtx 
-----

If you are a member of the WSJT Devopment Group and have commit privileges
to the repository, use a command like this one:

[source,bash]
-----
svn co https://user@svn.berlios.de/svnroot/repos/wsjt/branches/wsjtx
-----

substituting your Berlios username for +user+.

CAUTION: Please note: the HEAD of the SVN repository for any of these
programs is likely to be an active development branch.  There is no
guarantee that a build from every revision will be successful, nor
that it will provide a stable executable program.

== WSJT-X
include::wsjtx-dev.adoc[]

[appendix]
License
-------
include::../../global/license.adoc[]

