[[BASE_ENV]]
As a developer, one knows, there are many ways in which to set-up for 
developing a particular application. When using *JTSDK*, a structured 
environment is used in order to produce repeatable results. When using 
*JTSDK* (Windows or Linux), the user should not be required to install
any additional packages in order to checkout and build any of the _WSJT_
application or documentation.

=== Windows
*JTSDK* for Windows provides the containment and includes all required tools to
build a fully working application or the sub-targets if desired. Details of
each kit can be found in the appropriate appendix. With the exception of the
prerequisite packages, none of the packages within JTSDK should interfere nor
conflict with previously installed system packages.

.There are (4) primary environments
[horizontal]
*JTSDK-QT*:: used for building _WSJT-X, _WSPR-X_ and _MAP65_
*JTSDK-PY*:: used for building _WSJT_ and _WSPR_
*JTSDK-DOC*:: used for building documentation
*JTSDK-MSYS*:: a general purpose autotools environment

Each of the environments are completely isolated from one another, both
in terms of compilers and support package the paths. All (4) environments
are purpose built to provide the the correct configuration of packages.
While each may be customized by the user, care should be taken as to not break
the core configuration. 

All the packages used to build *JTSDK* (for Windows) are available on Sourceforge,
along with basic build instructions for each section.

=== Linux
*JTSDK* for Linux contains all builds and src folders within the users ($USER)
home directory. Unlike the Windows collection, Linux packaging is done by way
of the respective distribution package manager. The following distributions
are currently supported:

* Ubuntu; 14.04, 14.10
* Debian; 8.0*
* MIntl 17.1

As time allows, other distributions will be added.
