[[BASE_ENV]]
As a developer, one knows, there are many ways in which to set-up for 
developing a particular application. *JTSDK* employs a structured 
environment in order to produce repeatable results. All build scripts are
written to work with the *JTSDK* install locations. Modification of the scripts
is possible, but would entail a great deal of re-work.

If the user wants to build applications manually, the environment scripts,
(on Windows) provide the correct paths to all the required libraries and GCC
tool chains. Building outside of the environment is possible, but would require
setting the correct paths and ensuring system wide installation of the same or
similar tools do not conflict one another.

=== Suported Builds
The following matrix outlines which packages are supported by *JTSDK*.

[[SUPPORTEDBUILDS]]
.Build Matrix
[cols="^2m,^1,^2,^1,^2,^1,5"]
|===
|System|WSJT|WSJT-X|WSPR|WSPR-X|MAP65|Supported Arch

|Windows
|{y}
|{y}
|{y}
|{y}
|{y}
|32bit, runs on 64bit

|Linux
|{y}
|{y}
|{y}
|{n}
|{n}
|i386, amd64, armhf, ppc64el

|Mac OSX
|{y}
|{y}
|{y}
|{n}
|{n}
|i386, amd64

|iMac G4/G5
|{y}
|{y}
|{y}
|{n}
|{n}
|32bit OS, 64bit Kernel via ppc64el

|===

.Development Needs
****
At the time of this writing, **_WSPR-X_** and **_MAP65_** do not build on
Linux, Mac OSX or iMac. If you would like to join the development team and work any
of the packages, make your desires known to the {dev_mail_list} or email
*Joe Taylor* {joe_taylor}, to discuss helping out.
****

=== System Paths
On Linux / OSX, the applications are separated in three ways, by the application
name, version and subversion commit number. Currently, Windows does not use the
Subversion separator, but will in future releases. For **_WSJT-X_**, **_MAP-65_**
and **_WSPR-X_** there are (2) additional levels, Release and Debug, both for
install and build tree locations.

[[PATHLOCATIONS]]
.JTSDK Folder Locations
[options="header,autowidth"]
|===
|Platform|Type|Location

|Windows
|
Install Location +
Source Directory +
App Install Location +
Libraries +
Environments +
|
C:\JTSDK +
C:\JTSDK\src +
C:\JTSDK\(app name) +
C:\JTSDK\(library name) +
C:\JTSDK\JTSDK-(QT, PY, DOC, MSYS) +

|Linux
|
Install Location +
Source Directory +
App Install Location +
Libraries +
Environments +
|
/usr/local/bin +
/home/$USER/jtsdk/src +
/home/$USER/jtsdk/(app name) +
System Default Location +
System Default (sh, tcsh, ksh, bash) +
|===

=== Path Examples
**_WSJT_** and **_WSPR_** do not have multiple branches, debug and release
targets. The data below represents typical build flow data as it is today.

.Example Data
* **_WSJT-X_**,  **_1.7.0_**,  **_Development_**,  **_Release_**,  **_6133_**
* **_WSJT_**,  **_10.0_**,  **_6051_**

[[PATHLOCATIONS]]
.Path Locations Using Example Data
[options="header,autowidth"]
|===
|Name|Directory|Path

|WSJT-X
|
Source +
Build +
Install +
Package +

|/home/$USER/jtsdk/src/wsjtx +
/home/$USER/jtsdk/wsjtx/1.7.0/6133/build/Release +
/home/$USER/jtsdk/wsjtx/1.7.0/6133/install/Release +
/home/$USER/jtsdk/wsjtx/1.7.0/6133/package +


|WSJT
|
Source +
Build +
Install +

|/home/$USER/jtsdk/src/trunk +
/home/$USER/jtsdk/src/trunk +
/home/$USER/jtsdk/wsjt/10.0/6051/install +
|===

The application paths will increment with each svn commit. This allows
for testing each respoitory revision individually. The location will only be
incremented **_IF_** the change occurs to the branch, not the revision of
the repository.

TIP: Note the differene between ( _Debug_ ) and ( _Release_ ) for
the **_WSJT-X v1.7.0_** example. This type of separation is for aplications
built with *Cmake*:  **_WSJT-X_**, **_WSPR-X_** and **_MAP65_**.

.Linux Directory Tree for: WSJT-X v1.7.0
----
/home/$USER/jtsdk/wsjtx/1.7.0
├── 6131
│   ├── build
│   │   └── Release
│   ├── install
│   │   └── Release
│   └── package
└── 6133
    ├── build
    │   ├── Debug
    │   └── Release
    ├── install
    │   ├── Debug
    │   └── Release
    └── package
----

.Linux Directory Tree for: WSJT 10.0
----
/home/$USER/jtsdk/wsjt/10.0
├── 6047
│   └── install
└── 6051
    └── install
----

=== Windows Notes
*JTSDK-WIn32* provides the containment and all required tools to build a
fully working application or the sub-target if desired. Details of each kit can
be found in the appropriate appendix.

NOTE: **_JTSDK-Maint_** has access to all the general Unix type tools, _grep_,
_awk_, _rm_, _which_, etc and Subversion. It *does not* have a path set
for any of the GCC Tool-Chains.

.JTSDK-Nix Environments
[options="header,autowidth"]
|===
|Environment|Purpose

|JTSDK-QT
|used for building **_WSJT-X_**, **_WSPR-X_** and **_MAP65_**

|JTSDK-PY
|used for building **_WSJT_** and **_WSPR_**

|JTSDK-DOC
|Cygwin-32, used for building documentation

|JTSDK-MSYS
|MSYS with autotools, used for building **_Hamlib3_**

|JTSDK-Maint
|used for updates and upgrades
|===

.A Word of Caution
****
For *JTSDK-Win*, each of the environments are completely isolated from
one another, both in terms of compilers and support package paths. All
environments are purpose built to provide the the correct configuration
needed to build their respective packages. While environments may be customized
by the user, care should be taken so as not to break the core configuration, in
particular, the support libraries and respective GCC tool chains. This is
especially important when dealing with Python3 modules that build
**_WSJT_** and **_WSPR_** as they are version and compiler specific.
****

=== Linux Notes
*JTSDK-Nix*  packaging is done with a distribution package manager or from
the source tarball. Supported distributions can be found in the
<<INSTALLLINUX,Installation Section>>.

Rather than separate environments, *JTSDK-Nix* simply runs in the users default
environment, which provides access all system resouroces. Builds are
accomplished though a simple Dialog Ncurses menu rather than command line entry.
