[[BASE_ENV]]
As a developer, one knows, there are many ways in which to set-up for 
developing a particular application. **_JTSDK_** employs a structured 
environment in order to produce repeatable results. All build scripts are
written to work with the **_JTSDK_** install locations. Modification of the scripts
is possible, but would entail a great deal of re-work.

If the user wants to build applications manually, the environment scripts,
(on Windows) provide the correct paths to all the required libraries and GCC
tool chains. Building outside of the environment is possible, but would require
setting the correct paths and ensuring system wide installation of the same or
similar tools do not conflict one another.

On Linux, most, if not all of the required dependencies, are installed to system
folder locations. If you installed **_JTSDK_** from the configure scripts, no 
additional configuration should be required.

*****
WARNING: The **_JTSDK_** install location ( on **_Windows_** ) is fixed due to the fact
Python3 and Qt5 have been previously installed, or in the case of Python3
modules, built with a specific file / folder combination. While it is possible to
rebase both Python3 and Qt5, there is a risk of module failure in doing so. If
your planning on changing the install location, all of the build and support
scripts will need to be changed. It is highly advisable to leave the
default installation location as is.
*****

=== System Paths
On Linux / OSX, the applications are separated in three ways, by the application
name, version and subversion commit number. Currently, Windows does not use the
Subversion separator, but will in future releases. For **_WSJT-X_**, **MAP-65_**
and **_WSPR-X_** there are (2) additional levels, Release and Debug, both for
install and the build tree locations.

[[PATHLOCATIONS]]
.JTSDK Folder Locations
[options="header,autowidth"]
|===
|Platform|Type|Location

|Windows
|
Install Location +
Source Directory +
App Install Location +
Libraries +
Environments +
|
C:\JTSDK +
C:\JTSDK\src +
C:\JTSDK\(app name) +
C:\JTSDK\(library name) +
C:\JTSDK\JTSDK-(QT, PY, DOC, MSYS) +

|Linux
|
Install Location +
Source Directory +
App Install Location +
Libraries +
Environments +
|
/usr/local/bin +
/home/$USER/jtsdk/src +
/home/$USER/jtsdk/(app name) +
System Default Location +
System Default (sh, tcsh, ksh, bash) +
|===

=== Path Examples
**_WSJT_** and **_WSPR_** do not have multiple branches, debug and release
targets. The data below represents typical build flow data as it is today.

.Example Data
* **_WSJT-X_**,  **_1.6.0_**,  **_Development_**,  **_Release_**,  **_6073_**
* **_WSJT_**,  **_10.0_**,  **_6032_**

[[PATHLOCATIONS]]
.Path Locations Using Example Data
[options="header,autowidth"]
|===
|Name|Directory|Path

|WSJT-X
|
Source +
Build +
Install +
Package +

|/home/$USER/jtsdk/src/wsjtx +
/home/$USER/jtsdk/wsjtx/1.6.0/6073/build/Release +
/home/$USER/jtsdk/wsjtx/1.6.0/6073/install/Release +
/home/$USER/jtsdk/wsjtx/1.6.0/6073/package +


|WSJT
|
Source +
Build +
Install +

|/home/$USER/jtsdk/src/trunk +
/home/$USER/jtsdk/src/trunk +
/home/$USER/jtsdk/wsjt/10.0/6032/install +
|===

The application paths will increment with each svn commitment. This allows
for testing eeach respoitory commit individually. It should be noted, the 
location will only be incremented **_IF_** the change occurs to the branch,
not the the revision of the repository. Meaning, if a commit is made to
**_WSJT_**, it's svn revision would become **_6051_**. A new path would
be created for **_WSJT_**, but, **_WSJT-X_** would remain **_6073_**.

.WSJT-X v1.6.1 Directory Tree for Linux
----
/home/ki7mt/jtsdk/wsjtx/1.6.1
├── 6056
│   ├── build
│   │   └── Release
│   ├── install
│   │   └── Release
│   └── package
├── 6059
│   ├── build
│   │   └── Release
│   ├── install
│   │   └── Release
│   └── package
└── 6073
    ├── build
    │   └── Release
    ├── install
    │   └── Release
    └── package
----

.WSJT 10.0 Directory Tree for Linux
----
/home/$USER/jtsdk/wsjt/10.0
├── 6005
│   └── install
├── 6045
│   └── install
├── 6046
│   └── install
├── 6047
│   └── install
└── 6051
----

=== Windows Notes
**_JTSDK-Win32_** provides the containment and all required tools to build a
fully working application or the sub-target if desired. Details of each kit can
be found in the appropriate appendix.

NOTE: **_JTSDK-Maint_** has access to all the general Unix type tools, _grep_,
_awk_, _rm_, _which_, etc and Subversion. It **_does not_** have a path set
for any of the GCC Tool-Chains.

.JTSDK-Nix Environments
[options="header,autowidth"]
|===
|Environment|Purpose

|JTSDK-QT
|used for building **_WSJT-X_**, **_WSPR-X_** and **_MAP65_**

|JTSDK-PY
|used for building **_WSJT_** and **_WSPR_**

|JTSDK-DOC
|Cygwin-32, used for building documentation

|JTSDK-MSYS
|MSYS with autotools, used for building **_Hamlib3_**

|JTSDK-Maint
|used for updates and upgrades
|===

.A Word of Caution
****
For **_JTSDK-Win_**, each of the environments are completely isolated from
one another, both in terms of compilers and support package paths. All
environments are purpose built to provide the the correct configuration
needed to build their respective packages. While environments may be customized
by the user, care should be taken so as not to break the core configuration, in
particular, the support libraries and respective GCC tool chains. This is
especially important when dealing with Python3 modules that build
**_WSJT_** and **_WSPR_** as they are version and compiler specific.
****

=== Linux Notes
**_JTSDK-Nix_**  packaging is done with a distribution package manager or from
the source tarball. Supported distributions can be found in the
<<INSTALLLINUX,Installation Section>>.

Rather than separate environments, **_JTSDK-Nix_** simply runs in the users default
environment, which provides access all system resouroces. Builds are
accomplished though a simple Dialog Ncurses menu rather than command line entry.
