This section will guide you through the various steps of installation. For
<<INSTALLWINDOWS,Windows>>, the 32-Bit installer will configure all elements
from a single file. The <<INSTALLLINUX,Linux >> installation is through
traditional methods of configure, make, make install.

[[INSTALLWINDOWS]]
=== Windows
For your convenience, all packages can be downloaded from the {sourceforge-jtsdk}
files section. Using the links below, download each package, then proceed to
<<MSCVINSTALL,MSVC Redist Installation>>. Install the packages *In The Order Listed*:

[horizontal]
.Download Packages
*MSVC Redist 2010*:: {jtsdk-vcredist-2010}
*MSVC Redist 2013*:: {jtsdk-vcredist-2013}
*OmniRig*:: {jtsdk-omnirig}
*JTSDK Main Installer*:: {jtsdk-installer}
*Update 1*:: {jtsdk-update1}
*Update 2*:: {jtsdk-update2}
*Update 3*:: {jtsdk-update2}

[[MSCVINSTALL]]
==== MSVC Redist 2010
* Run the installer ( vcredist-x86.exe )
* Read and accept the terms
* Follow the prompts

==== MSVC Redist 2013
* Run the installer ( vcredist_msvc2013_x86.exe )
* Read and accept the terms
* Follow the prompts

==== OmniRig Installation
* Unzip the installer ( OmniRig.zip )
* Run the installer ( OmniRigSetup.exe )
* Follow the prompts

==== JTSDK Main Installation
* Run the installer ( JTSDK-2.0.0-win32.exe )
* Accept KVASD EULA
* Wait for primary instillation to complete
* Monitor Cygwin32 installation for any errors

==== Update-1
* Run the installer ( JTSDK-2.0.0-u1-win32.exe )
* Accept the defaults
* Follow the prompts

==== Update-2
* Run the installer ( JTSDK-2.0.0-u2-win32.exe )
* Accept the defaults
* Follow the prompts

==== Update-3
* Run the installer ( JTSDK-2.0.0-u3-win32.exe )
* Accept the defaults
* Follow the prompts


TIP: Due to the custom installation of JTSDK-MSYS, upon first run, the
environment will be set-up for your specific user.  You will be prompted to
re-start JTSDK-MSYS after it configures the shell. Or you can simply reload the
shell with a command: `exec $SHELL -l`


[[INSTALLLINUX]]
=== Linux
At the time of this writing, only Debian/Ubuntu based distributions are
supported for Linux.

IMPORTANT:  WSPR-X and MAP65 *are not* supported on Linux.

[[UBUNTUMINT]]
==== Install From PPA ( Ubuntu / Mint )
To install **_JTSDK-Nix_** from PPA (Debian packge from Launchpad), open a
terminal, and execute the following commands:

-----
sudo add-apt-repository -y ppa:ki7mt/jtsdk
sudo apt-get update
sudo apt-get install jtsdk
-----

==== Installation From Source Tarball
Installing from source code is fairly simple. Download, extract then run the 
standard commands for installing via source tarballs. You can obtain
the source tarball from: {jtsdk-nix}

IMPORTANT: When installing from the source tarball, it is the **_users responsibility_**
to ensure all package requirments are met, both for **_JTSDK-Nix_** and all
**_WSJT_** applications. This should be done **_before_** running the
autogeh.sh script. A package list if available, for select distribtions,
See {readmepkglist}.

Extract jtsdk-nix-2.0.16.tar.gz to a suitable location, then execute the following
commands in a termainl:

-----
cd ./jtsdk-nix-2.0.16
./autogeh.sh
make
sudo make install
-----

If there were no errors during configuration, build or install steps,
**_JTSDK-Nix_** is ready for use.


==== Run JTSDK
To run **_JTSDK-Nix_** form an open terminal, type: `jtsdk`. Or, search your menu
system for `jtsdk` and dboule click the icon.


==== Uninstall
To uninstall **_JTSDK-Nix_**, open a termainl and execute the following commands:

-----
# change directories to the location where you installed from
cd ./jtsdk-nix-2.0.16      
sudo make uninstall
-----

==== Upgrading
If you are upgrading **_JTSDK-Nix_** to a newer version, perform an *Uninstall*
first, then proceed with a normal source install.

==== POTENTIAL ISSUES

[WARNING]
====
- The Mint 17.1 / 17.2 Cinnamon Desktop installs python-numpy as part of it's
default installation. If you encounter `PObject Errors` when running **_WSPR_** or
**_WSJT_**, more than likely this is the cause.

- **_WSPR_** and **_WSJT_** require python3-numpy. To resolve, remove python-numpy,
but be warned, this may cause unexpected behavior in your Desktop Environment.
====
