For <<INSTALLWINDOWS,Windows>>, the 32-Bit installer(s) will configure all elements
from a single file. The <<INSTALLLINUX,Linux >> installation is through
traditional methods of configure, make, make install or the distribution package
manager.

[[INSTALLWINDOWS]]
=== Windows
For your convenience, all packages can be downloaded from the {sourceforge-jtsdk}
files section. Using the links below, download each package, then proceed to
<<MSCVINSTALL,MSVC Redist Installation>>. Install the packages *In The Order Listed*:

TIP: If you have previously installed *MSVC Redist 2010*, *MSVC Redist 2013* or
*OmniRig* {quot}AND{quot} did not remove them, you can start the installation
with the *JTSDK Main Installer*. If there is *any doubt*, install all the
packages.

[[WIN32DOWNLOADS]]
.Download Matrix
[options="header,autowidth"]

|===
|Package|Link|Description

|*MSVC Redist 2010*
|{jtsdk-vcredist-2010}
|MS Runtime DLLs for QT5 {amp} Python27

|*MSVC Redist 2013*
|{jtsdk-vcredist-2013}
|MS Runtime DLLs for QT5.5

|*OmniRig*
|{jtsdk-omnirig}
|WSJT-X Rig Control

|*JTSDK Main Installer*
|{jtsdk-installer}
|Main JTSDK Program Set

|*Update 1*
|{jtsdk-update1}
|Adds Python27 {plus} AsciiDoc

|*Update 2*
|{jtsdk-update2}
|Adds QT5.5 for Devel Testing

|*Update 3*
|{jtsdk-update3}
|Adds Ruby {plus} Asciidoctor
|===

[[MSCVINSTALL]]

.JTSDK-Win32 Fixed Install Location
*****
The *JTSDK-Win32* install location pass:q[*C:\JTSDK*] is fixed  due to the fact
Python3 and Qt5 have been previously installed, or in the case of Python3
modules, built with a specific file / folder combination. While it is possible to
rebase both Python3 and Qt5, there is a risk of module failure in doing so. If
your planning on changing the install location, all of the build and support
scripts will need to be changed. It is highly advisable to leave the
default installation location as is.
*****

IMPORTANT: You *must have* Internet access in order to perform the installation

With the exception of *OmniRig*, where you must Unzip the package first, 
all that is required is to run the respective installer ( [red]+++<u>In The Order Listed</u>+++ ),
accept the license terms, then following the prompts.

. Run vcredist-x86.exe, accept terms, contimue
. Run vcredist_msvc2013_x86.exe, accept terms, continue
. Unzip OmniRigSetup, then run the .exe file, follow the prompts
. Run JTSDK-2.0.0-win32.exe, accept terms, continue
. Run JTSDK-2.0.0-u1-win32.exe, accept terms, continue
. Run JTSDK-2.0.0-u2-win32.exe, accept terms, continue
. Run JTSDK-2.0.0-u3-win32.exe, accept terms, continue


NOTE: Due to the custom installation of JTSDK-MSYS, upon first run, the
environment will be set-up for your specific user.  You will be prompted to
re-start JTSDK-MSYS after it configures the shell. Or you can simply reload the
shell with a command: `exec $SHELL -l`

[[INSTALLLINUX]]
=== Linux

At the time of this writing, the following distributions are supported from
native package managers, *apt-get, dpkg, Gdebi* or *Synaptic*.

There may be additional *Debian* / *Ubuntu* distributions that *JTSDK Nix** 
will work with, the matrix below represents those that have been tested and
known to work properly.

.Supported Distributions




[[UBUNTUMINT]]
==== Install From PPA ( Ubuntu / Mint )
To install *JTSDK-Nix* from PPA (Debian packge from Launchpad), open a
terminal, and execute the following commands:

-----
sudo add-apt-repository -y ppa:ki7mt/jtsdk
sudo apt-get update
sudo apt-get install jtsdk
-----

==== Installation From Source Tarball
Installing from source code is fairly simple. Download, extract then run the 
standard commands for installing via source tarballs. You can obtain
the source tarball from: {jtsdk-nix}

IMPORTANT: When installing from the source tarball, it is the *your responsibility*
to ensure all package requirements are met, both for *JTSDK-Nix* and all
**_WSJT_** applications. This should be done *before* running the
``autogen.sh'' script. A package list if available, for select distributions,
See {readmepkglist}.

Extract jtsdk-nix-2.0.16.tar.gz to a suitable location, then execute the following
commands in a termainl:

-----
cd ./jtsdk-nix-2.0.16
./autogeh.sh
make
sudo make install
-----

If there were no errors during configuration, build or install steps,
*JTSDK-Nix* is ready for use.


==== Run JTSDK
To run *JTSDK-Nix* form an open terminal, type: `jtsdk`. Or, search your menu
system for `jtsdk` and dboule click the icon.


==== Uninstall
To uninstall *JTSDK-Nix*, open a terminal and execute the following commands:

-----
# change directories to the location where you installed from
cd ./jtsdk-nix-2.0.16      
sudo make uninstall
-----

==== Upgrading
If you are upgrading *JTSDK-Nix* to a newer version, perform an *Uninstall*
first, then proceed with a normal source install.

==== POTENTIAL ISSUES

[WARNING]
====
- The Mint 17.1 / 17.2 Cinnamon Desktop installs python-numpy as part of it's
default installation. If you encounter `PObject Errors` when running **_WSPR_** or
**_WSJT_**, more than likely this is the cause.

- **_WSPR_** and **_WSJT_** require python3-numpy. To resolve, remove python-numpy,
but be warned, this may cause unexpected behavior in your Desktop Environment.
====
