For <<INSTALLWINDOWS,Windows>>, the 32-Bit installer(s) will configure all elements
from a single file. The <<INSTALLLINUX,Linux >> installation is through
traditional methods of configure, make, make install or the distribution package
manager.

[[INSTALLWINDOWS]]
=== Windows
For your convenience, all packages can be downloaded from the {sourceforge-jtsdk}
files section. Using the links below, download each package, then proceed to
<<MSCVINSTALL,MSVC Redist Installation>>. Install the packages *In The Order Listed*:

TIP: If you have previously installed *MSVC Redist 2010*, *MSVC Redist 2013* or
*OmniRig* {quot}AND{quot} did not remove them, you can start the installation
with the *JTSDK Main Installer*. If there is *any doubt*, install all the
packages.

[[WIN32DOWNLOADS]]
.Download Matrix
[options="header,autowidth"]

|===
|Package|Link|Description

|*MSVC Redist 2010*
|{jtsdk-vcredist-2010}
|MS Runtime DLLs for QT5 {amp} Python27

|*MSVC Redist 2013*
|{jtsdk-vcredist-2013}
|MS Runtime DLLs for QT5.5

|*OmniRig*
|{jtsdk-omnirig}
|WSJT-X Rig Control

|*JTSDK Main Installer*
|{jtsdk-installer}
|Main JTSDK Program Set

|*Update 1*
|{jtsdk-update1}
|Adds Python27 {plus} AsciiDoc

|*Update 2*
|{jtsdk-update2}
|Adds QT5.5 for Devel Testing

|*Update 3*
|{jtsdk-update3}
|Adds Ruby {plus} Asciidoctor
|===

[[MSCVINSTALL]]

.JTSDK-Win32 Fixed Install Location
*****
The *JTSDK-Win32* install location pass:q[*C:\JTSDK*] is fixed  due to the fact
Python3 and Qt5 have been previously installed, or in the case of Python3
modules, built with a specific file / folder combination. While it is possible to
rebase both Python3 and Qt5, there is a risk of module failure in doing so. If
your planning on changing the install location, all of the build and support
scripts will need to be changed. It is highly advisable to leave the
default installation location as is.
*****

==== Windows Installation Steps

IMPORTANT: You *must have* Internet access in order to perform the installation

With the exception of *OmniRig*, where you must Unzip the package first, 
all that is required is to run the respective installer ( [red]+++<u>In The Order Listed</u>+++ ),
accept the license terms, then following the prompts.

. Run vcredist-x86.exe, accept terms, contimue
. Run vcredist_msvc2013_x86.exe, accept terms, continue
. Unzip OmniRigSetup, then run the .exe file, follow the prompts
. Run JTSDK-2.0.0-win32.exe, accept terms, continue
. Run JTSDK-2.0.0-u1-win32.exe, accept terms, continue
. Run JTSDK-2.0.0-u2-win32.exe, accept terms, continue
. Run JTSDK-2.0.0-u3-win32.exe, accept terms, continue


NOTE: Due to the custom installation of JTSDK-MSYS, upon first run, the
environment will be set-up for your specific user.  You will be prompted to
re-start JTSDK-MSYS after it configures the shell. Or you can simply reload the
shell with a command: `exec $SHELL -l`

[[INSTALLLINUX]]
=== Linux
Depending on your Linux distribution, **_JTSDK-Nix_** can be installed in one
of two methods, <<SOURCE_INSTALL_METHOD,Source Tarball>> or
<<PPA_INSTALL_METHOD,Launchpad PPA>>. The <<LINUX_INSTALL_METHOD,matrix>> below
outlines the preferred method for various distributions.

Installing **_JTSDK-Nix_** *Does Not* install the required build dependencies.
You must follow the guide recommendations outlined in the
<<DISTROPKGS, Linux Packaging>> section.

[[LINUX_INSTALL_METHOD]]
.Linux Preferred Installation Method
[cols="1,^1,1", options="header, autowidth"]
|===
|Distribution|Method|Package-Manager

|Debian
|PPA
|apt-get, gdebi, Synaptic

|Fedora
|Source Tarball
|autogen.sh, make, make install

|Linux Lite
|PPA
|apt-get

|Linux Mint
|PPA
|apt-get

|Ubuntu
|PPA
|apt-get

|===

[[PPA_INSTALL_METHOD]]
==== Install From PPA
To install *JTSDK-Nix* from PPA:

====
* Open a terminal kbd:[Ctrl + Alt + t], and execute the following commands:
-----
sudo add-apt-repository -y ppa:ki7mt/jtsdk
sudo apt-get update
sudo apt-get install jtsdk
-----
* After installing JTSDK-Nix, follow the guide for your distribution build dependencies
found in <<DISTROPKGS,Linux Packaging>> section.
====

[[SOURCE_INSTALL_METHOD]]
==== Installation From Source Tarball
When installing from the source tarball, it is the *your responsibility*
to ensure all package requirements are met, both for *JTSDK-Nix* and all
**_WSJT_** applications. This should be done *before* running the
``autogen.sh'' script. See <<DISTROPKGS,LInux Packaging>> for distribution
specific instruction.

Once all the dependencies have been met, installing from source code is fairly
simple. Download, extract then run the standard commands for installing via
source tarballs. You can obtain the source tarball from: {jtsdk-nix}

====
Extract jtsdk-nix-2.0.17.tar.gz to a suitable location, then execute the following
commands in a terminal:

-----
cd ./jtsdk-nix-2.0.17
./autogen.sh
make
sudo make install
-----

If there were no errors during configuration, check the distribution 
<<LINUX_INSTALL_METHOD,matrix>> for any additional actions, then
*JTSDK-Nix* is ready for use.
====

==== Run JTSDK
====
* Open a terminal, kbd:[Ctrl + Alt + t], then type: `jtsdk`
* Alternatively, search your menu system for `jtsdk` and double click the icon.
====

==== Uninstall
To uninstall *JTSDK-Nix*, open a terminal and execute the following commands:

==== Uninstall via PPA
====
* In a terminal kbd:[Ctrl + Alt + t], type:
-----
sudo apt-get remove jtsdk
-----
====

==== Uninstall via Source
====
* In a terminal kbd:[Ctrl + Alt + t], change directories to the location where
you installed JTSDK-Nix from, then uninstall.
-----
cd ./jtsdk-nix-2.0.17    
sudo make uninstall
-----
====
