Dependency management is an area that can casue a great deal of confusion. There
are many types of dependencies, however, for this guide, we are mainly concerned
with *Build* depeendencies.

* Each section will list the primnary build dependencies, special notes or known
issues and how best to resolve them.

* In some cases, where package incompatibilties exist, a special note will be
provided if it has been tested. 

The following distributions version combinations have been tested or are known to
work with minimal package system manipulation.

[[LINUX_DISTRO_MATRIX]]
.Distribution Matrix
[cols="1,^1,^1,^1,^1,^1", options="header, autowidth"]
|===
|Distrbution|Arch|Desktop|Version|Code Name|Remarks

|Debian
|i386, amd64
|Gnome3
|8.0 +
9.0
|Jessie +
Sid
|
{sr} {ub} +
{sg} {ub}

|Fedora
|i386, amd64
|Gnome3
|21 +
22 +
23 +
|21 +
22 +
23 +
|{sg} +
{sg} +
{sg}

|Linux Lite
|i386, amd64
|Mate
|2.6
|Lite
|
{sr} {sb} {ub}

|Linux Mint
|i386, amd64
|Mate
|17.2
|Rebecca
|
{sr} {sb} {ub}

|Ubuntu
|i386, amd64, armhf, ppc64el
|Unity
|
14.04 +
15.04 +
15.10 +
16.04
|
Trusty +
Vivid +
Wily +
Xenial
|
{sr} {ub} +
{sg} {ub} +
{sg} {ub} +
{sg} {ub}
|===

{sr} - Requies manual Asciidoctor installation. <<ASCIIDOCTOR_INSTALL,See - Install Asciidoctor>> +
{sb} - Possible Jackd2 conflict, <<JACKD2_NOTE,See Special Note>> +
{ub} - User must be in the dialout group. <<DIAOUT_GROUP,See - Add user to dialout group>> +
{sg} - No Known Issues

'''

[[DEBIAN_SETUP]]
=== Debian

Install process tested on: *Debian 8.0*

Due to a repository package incompatability in python3-pil, additional packages
and steps are required in order to build WSJT and WSPR.

Install dependencies first, then install Python3 Pillow using Pip3.

* Open a termainl kbd:[Ctrl + Alt + t], and install the build dependencies
-----
sudo apt-get install automake asciidoctor clang-3.5 cmake dialog g++ gettext \
gfortran git libfftw3-dev libhamlib-dev libhamlib-utils libqt5multimedia5 \
libqt5multimediawidgets libqt5multimedia5-plugins libqt5serialport5-dev \
libqt5opengl5-dev libsamplerate0-dev libtool libusb-dev libxml2-utils \
pkg-config portaudio19-dev python3-imagetk python3-tk python3-dev \
python3-numpy python3-pip python3-setuptools python-dev qtbase5-dev \
qtmultimedia5-dev source-highlight subversion ruby texinfo xmlto \
libfreetype6-dev libjpeg-dev liblcms2-dev libtiff5-dev libwebp-dev \
libwebpmux1 mime-support tcl8.6-dev tk8.6-dev zlib1g-dev
-----

=====
* Once the installation is complete, install Pillow with
-----
sudo pip3 install pillow
-----
* Install Asciidoctor anually, see <<ASCIIDOCTOR_INSTALL, Installing Asciidoctor>>
* Ensure your user is in the *dialout* group, see <<DIAOUT_GROUP, How-Too>>
* Now you can run run *JTSDK* and build the applications from the main menu.
=====

'''

[[FEDORA_SETUP]]

=== Fedora

Install process tested on: *(none)*

Several users in the {wsjt-yahoo-group} or users who contribute regularly to the
{dev-mail-list} run *JTSDK* on *Fedora*, however, at the time of this writing, we
do not have a package list nor specific install instructions.

If you have a firm install procedure and wish to include it, send the
informattionto the {dev-mail-list}.

[[MINT_SETUP]]
=== Linux Mint

Install process tested on: *Mint 17.2*

On Linux Mint, audio selection can be problematic. The package list below has
been updated with the solutions that resolved this for several users. If you
still hae Audio Selection problems with **_WSJT-X_**, report it to the
{dev-mail-list} 

====
* Open a termainl kbd:[Ctrl + Alt + t], and install the build dependencies
-----
sudo apt-get install automake asciidoc clang-3.5 cmake dialog g++ gettext \
gfortran git libfftw3-dev libhamlib-dev libhamlib-utils libqt5multimedia5 \
libqt5multimedia5-plugins libqt5multimediawidgets libqt5serialport5-dev \
libqt5opengl5-dev libsamplerate0-dev libtool libusb-dev libxml2-utils \
pkg-config portaudio19-dev python3-pil python3-pil.imagetk python3-tk \
python3-dev python3-numpy python3-pip python3-setuptools python-dev qtbase5-dev \
qtmultimedia5-dev ruby source-highlight subversion texinfo xmlto
-----
* Install Asciidoctor manually, see <<ASCIIDOCTOR_INSTALL, Installing Asciidoctor>>
* Ensure your user is in the *dialout* group, see <<DIAOUT_GROUP, How-Too>>
* See <<JACKD2_NOTE, Special Note>> regarding Jackd configuration
* Now you can run run JTSDK and build the applications from the main menu.
====

[WARNING]
====
- The Mint 17.1 / 17.2 Cinnamon Desktop installs python-numpy as part of it's
default installation. If you encounter `PObject Errors` when running **_WSPR_** or
**_WSJT_**, more than likely this is the cause.

- **_WSPR_** and **_WSJT_** require python3-numpy. To resolve, remove python-numpy,
but be warned, this may cause unexpected behavior in your Desktop Environment.
====

'''

[[LITE_SETUP]]
=== Linux Lite

Install process tested on: *Lite 2.6*

====
* Open a termainl kbd:[Ctrl + Alt + t], and install the build dependencies
-----
sudo apt-get install automake asciidoc clang-3.5 cmake dialog g++ gettext \
gfortran git libfftw3-dev libhamlib-dev libhamlib-utils libqt5multimedia5 \
libqt5multimedia5-plugins libqt5multimediawidgets libqt5serialport5-dev \
libqt5opengl5-dev libsamplerate0-dev libtool libusb-dev libxml2-utils \
pkg-config portaudio19-dev python3-pil python3-pil.imagetk python3-tk \
python3-dev python3-numpy python3-pip python3-setuptools python-dev qtbase5-dev \
qtmultimedia5-dev ruby source-highlight subversion texinfo xmlto
-----
* Install Asciidoctor manually, see <<ASCIIDOCTOR_INSTALL, Installing Asciidoctor>>
* Ensure your user is in the *dialout* group, see <<DIAOUT_GROUP, How-Too>>
* Now you can run run JTSDK and build the applications from the main menu.
====

'''

[[UBUNTU_SETUP]]
=== Ubuntu

Install process tested on: *Ubuntu 14.04*, *15.04*, *15.10* and *16.04*

The default installation was performed on Unity. The package list should
also work for Lubuntu, Xubuntu and Kubuntu.

====
* Open a termainl kbd:[Ctrl + Alt + t], and install the build dependencies
-----
sudo apt-get install automake asciidoc clang-3.5 cmake dialog g++ gettext \
gfortran git libfftw3-dev libhamlib-dev libhamlib-utils libqt5multimedia5 \
libqt5multimedia5-plugins libqt5multimediawidgets libqt5serialport5-dev \
libqt5opengl5-dev libsamplerate0-dev libtool libusb-dev libxml2-utils \
pkg-config portaudio19-dev python3-pil python3-pil.imagetk python3-tk \
python3-dev python3-numpy python3-pip python3-setuptools python-dev qtbase5-dev \
qtmultimedia5-dev ruby source-highlight subversion texinfo xmlto
-----
* Install Asciidoctor anually, see <<ASCIIDOCTOR_INSTALL, Installing Asciidoctor>>
* Ensure your user is in the *dialout* group, see <<DIAOUT_GROUP, How-Too>>
* Now you can run run JTSDK and build the applications from the main menu.
====

'''

[[DIAOUT_GROUP]]
=== Dialout Group

On Debian / Ubuntu based systems, the user must be in the *dialout*
in order to use, set or other wise manipulate comports (STTY or USB). To ensure
your user is in the dialout group, perform the following  (before installing
package dependencies ).

====
* Open a terminal kbd:[Ctrl + Alt + t], then type: groups
* If you do not see your user in the list, add it with:
-----
sudo adduser $USER dialout 
-----
* Logout out, back in, recheck, and continue.
====

'''

[[ASCIIDOCTOR_INSTALL]]
=== Asciidoctor Install
Some distributions, Ubuntu 14.04 (Trusty) and Debian 8.0 (Jessie) for example,
do not meet the minimum Asciidoctor version requirment ( *v1.5.3* ) for building
**_WSJT-X v1.7.0_**. This can easily be resolved by installing Asciidoctor
through the Gem Module Manager. If your distribution Asciidoctor package *is not*
at least ( *v1.5.3* ), install Asciidoctor as follows:

TIP: RubyGems is a package manager for the Ruby programming language that
provides a standard format for distributing Ruby programs and libraries (in
a self-contained format called a "gem"). Gem package manager is similar in
function to Python Pip.

====
* Open a terminal kbd:[Ctrl + Alt + t]
* Install *Ruby* and *Asciidoctor*:
-----
sudo apt-get install ruby
sudo gem install asciidoctor
-----
* Update shell after gem installation:
-----
exec $SHELL -l
-----
* Check Asciidoctor version:
-----
asciidoctor --version
-----

You should see both Ruby and the Asciidoctor versions listed, something
along the lines of:

-----
Asciidoctor 1.5.3 [http://asciidoctor.org]
Runtime Environment (ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux])
(lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
-----
====

'''

[[JACKD2_NOTE]]
=== Jackd2 Specail Note
On some Debian / Ubuntu distributions, during the installation of portaudio19-dev,
Jack2 may be uninsatalled. If you are using Jackd2 for other applications, you
should be able to re-install it without affecting the portaudio19-dev package.

