// Taken from WSJT Main Website
_WSJT, MAP65, WSPR, and WSJT-X_ are open-source programs designed for
weak-signal digital communication by amateur radio. Normal usage requires a
standard SSB transceiver and a personal computer with soundcard. SDR-style
hardware including the SDR-IQ, Perseus, SoftRock, and FUNcube Dongle is supported
by MAP65 and WSPR. SimJT is a utility program that generates simulated signals for
test purposes.

It should be noted, building _WSJT_ applications can be extremely challenging.
*JTSDK* provides a preconfigured set of packages and custom build scripts which
allow a user to build all of the main applications with minimal effort. However,
the default scripts may not be suitable for those actively developing applications
in all cases. To aid the core developers, several tools have been included that
allow for much greater flexibility in their final outputs, yet still maintain 
the core building tools for consistency.

=== Core Features
While the implementation may differ slightly, both *JTSDK* for <<WINSDK,Windows>>
and <<NIXSDK,Linux>> provide canned build scripts to compile _WSJT_ applications
from source code. The core features are listed below. for each kit.

[[WINSDK]]
.JTSDK Win32* provides the following core features:
* Supported applications: ( ALL )
* QT5 + mingw32 (GCC 4.8.0) winpthread Tool Chain
* MinGW32 (GCC 4.8.1) pthread Tool Chain
* MSYS Base Environment {plus} Autotools
* Cygwin 32Bit Env, Bash, Gnu Coreutils, Git, SVN {plus} much more ...
* Python2 and Python3 with Tcl/Tk in Separate Environments
* InnoSetup and NSIS installer building tools
* Build Scripts methods for All WSJT Documentation
* Supports Win32/64 and Linux x86/x86-64

[[NIXSDK]]
.JTSDK Nix* provides the following core features:
* Supported Applications: ( _WSJT, WSPR, WSJTX, Hamlib3_ )
* Automated distribution package installation
* Ncurses menu (command line) for building supported applications
* Build Scripts methods for All WSJT Documentation

=== Core Functions
This guide will provide users with the following guidance:

* Installing prerequisites packages
* Installing JTSDK on ( <<INSTALLWINDOWS,Windows>> and <<INSTALLLINUX,Linux>> ) 
* Overview of packages, libraries and frameworks
* Building each application using default configurations
* Command line custom configuration builds
* Outline available tools and script capabilities
* A brief introduction to using QtCreator for builds
* Basic How-Too using Cmake-Gui

In addition to the core application build tools, each environment provides a
host of very powerful command line tools. A detailed list is provided in the
appendix, however, it is up to the user to research how best to employ each tool
to fully leverage the SDKs potential.

On Windows, *JTSDK*, by design, should not interfere with any previously
installed development packages. If you find or have a conflict, please report it
to the {dev_mail_list}.
