**_WSJT_**, **_WSJT-X_**, **_WSPR_**, **_WSPR-X_**, and **_MAP65_** are
open-source programs designed for weak-signal digital communication by amateur
radio. Normal usage requires a standard SSB transceiver and a personal computer
with soundcard. SDR-style hardware including the SDR-IQ, Perseus, SoftRock, and
FUNcube Dongle is supported by **_MAP65_** and **_WSPR_**. **_SimJT_** is a utility
program that generates simulated signals for test purposes.

It should be noted, building **_WSJT_** applications can be challenging.
*JTSDK* provides a preconfigured set of packages and custom build scripts which
allow a user to build ( _compile_ ) all of the main applications with minimal
effort. However, the default scripts may not be suitable for those actively
developing applications in all cases. To aid the core developers, many tools
have been included that allow for much greater flexibility in their final
outputs, yet still maintain the core building tools for consistency.

.Join The Development Team
****
If you would like to join the development team and work any of the applications,
documentation, build systems, packaging; make your desires known to the {dev-mail-list},
or email *Joe Taylor* {joe-taylor}, to discuss helping out.
****

=== About This Guide
.What This Guide *_"IS"_*
The purpose of the {page} is to walk through the variaous elements of bulding
each of the **_WSJT_** applications {amp} their associated documentation. The
guide will, as time allows, be updated to include ( _basic_ ) operation of major
tools such as *Cmake-gui*, *QtDesigner* and the like. It will also include,
again, as time allows, a brief introcuction to tools used by developers
specific to **_WSJT_** applications themself, such as jt9sim, and command line
operation of various binaries each package builds.

.What This Guide *_"IS NOT"_*
{page} does not go into any of the source code construction, functions or
architectural composition. Those discussions are left to the ( _Core Development
Team_ ), generally discussed on the {dev-mail-list}.

.What The Scripts *_"PROVIDE"_*
All the build scripts in *JTSDK* proved a default build for each of the
various applications and their associated user guide when available. The intension
is to create repeatable results providing a high level of consistency. In
no way should the default build(s) place limititations on more experienced
devlopers. Rahter, the scripts should be considered an aid to troubleshooting
as the average user will not be changing the default build constructs. Thus 
providing the experinced developer with a know set of variables used to build
the application if and when a problem is identified.

.Help Improve This *_"GUIDE"_*
Many of the **_WSJT_** applications are under constant revision. As such,
changes to the build system, source locations, method of construction and other
key aspects can, and often do, change form day to day. The {page}
may not be 100% accurate, but should represent a reasonable reflection of
what is currently in use by the ( _Core Development Team_ ). If you find a
section that is out of date, needs revision, or no longer makes sense due to
rescent development activity, send a message the {dev-mail-list}.

Additionally, if you feel something should be added, modified, omitted or 
otherwise adjusted in {page}, send your recommendations {dev-mail-list}.

=== The Command Line
With {page}, all work is performed from the ( _Command Line_ ), *DOS Console* 
on Windows, *Bash Shell* on Linux. There is no Graphical User Interace 
( _GUI_ ), Widgets or Point {amp} Click interface associated with the scripts.
Without question, there are *_PROS_* {amp} *_CONS_* to both methods, however,
this guide will not discuss the merits of either approach.

Do not confuse this with the absence of Framework UI's such as *QtDesigner* or
*Cmake-Gui*. All of the the UIs that accompany each package are included in 
*JTSDK*, just as if you installed the package(s) yourself. They are made readily
available to the user, in most cases, with a Desktop Shortcut or Program Menu
entry.

It is understood, not all users of *JTSDK* are experts in Command Line Foo. Every
attempt has been made to *_make compiling as easy as possible_* for those new
to building applications from source code, while not placing limitations on the
more advaced users.

=== Core Elements
While the implementation may differ slightly, both *JTSDK* for <<WINSDK,Windows>>
and <<NIXSDK,Linux>> provide similar core features.

.Hundreds of Usefull Tools
****
In both *JTSDK-Win32* and *JTSDK-Nix*, there are literaly hundreds of tools
and applications available to the user. The <<COREFEATURES,Core Elements Table>>
outlines the base Frameworks, Tool-Chains, and Libraries used to compile all
**_WSJT_** applications. For a detailed list, per application, see the
<<PKGMATRIX,Package Matrix>>
****

[[COREFEATURES]]
.JTSDK Core Elements
[options="header,autowidth"]
|===
|Platform|Features|Comments

|Windows
|
Applications Builds +
QT-5.0 +
QT-5.5 +
QtCreator +
Cmake +
MinGW32 +
MSYS Base Environment +
Cygwin Environment +
Python2 and Python3 +
InnoSetup and NSIS +
Subversion, Git +
Asciidoctor +
|
WSJT-X, WSJT, WSPR, MAP65, WSPR-X, Hamlib3 +
GCC 4.8 WinPthreads +
GCC 4.9 WinPthreads +
Cross-Platform IDE +
Cross-Platform Build System +
GCC 4.8.1 Ptheads +
GNU Autotools +
Bash, Coreutils, {plus} much more +
Intreputer, Tcl/Tk, required modules +
Win32 Installer Design Tools +
Repository Management Tools +
Documentation Design Tool +

|Linux
|
Application Build sub-set +
Distribution Package +
Source package availabe +
Ncurses Menu +
Build Scripts +
|
WSJT-X, WSJT, WSPR, Hamlib3 +
Available for Debian based distros +
Source tarball for non .deb distros +
Command Line menu system +
Canned scrtipts for consistency +
|===

.Cross Platform Access
* With the exception of Windows specific applications, things line InnoSetup,
Mingw32, Cygwin, MSYS; all of the tools available for Windows can be accessed
on a Linux / OSX system and have not been listed specifically.

.Command Line Tools
* In addition to the core application build tools, each environment provides a
host of very powerful command line tools. A detailed list is provided in the
appendix, however, it is up to the user to research how best to employ each tool
to fully leverage the SDKs potential.

.Syetem Interference
* On Windows, *JTSDK-Win32*, by design, *should not* interfere with
any previously installed development packages. If you find or have a conflict,
please report it to the {dev-mail-list}.

=== Special Terms
The following is a short list of special terms used throught this guide, and their
intended meaning.

* **_Windows_**: refers to all version of Windows, Vista, 7, 8, and 10
* **_Linux_**: refers to all versions of Linux, Unix and BSD.
* **_JTSDK-Win32_**: refers to *JTSDK* on Windows
* **_JTSDK-Nix_**: refers to *JTSDK* on Linux
