=== Linux Makefile Example

In order to build _WSJT-X_ form source, the install the following packages:

----------
sudo apt-get install gcc g++ gfortran make libqt5multimedia5-plugins \
libfftw3-dev libpulse-dev libhamlib-dev qtbase5-dev qtmultimedia5-dev \
pulseaudio subversion install libgfortran3:i386 libc6-i386
----------

Adjust accordingly for you Linux distribution package manager.

==== Dependency Descriptions
[horizontal]
+gcc+:: GNU C Compiler
+g{plus}{plus}+:: GNU C{plus}{plus} Compiler
+gfortran+:: GNU Fortran or F90
+make+:: GNU Make
+libqt5multimedia5-plugins+:: QT5 Media Plugins
+libfftw3-dev+:: Fast Fourier Transforms
+libpulse-dev+:: Headers and Files for Pulse AUdio
+libhamlib-dev+:: Headers and Files for Hamlib
+qtbase5-dev+:: QT5 Base Dev Files
+qtmultimedia5-dev+:: Qt5 Multimedsia Dev Files
+pulseaudio+:: Pulse Audio Sound Driver
+subversion+:: Version Control Software
+libgfortran.so.3+:: 32-Bit Fortran Library
+libc.so.6+:: 32-bit C Library
+libm.so.6+:: 32-bit C Library
+libgcc_s.so.1libm.so.6+:: 32-bit C Library 
+libquadmath.so.0+:: 32-Bit Quad-Precision Math Library

==== Set-Up Directories
Open a terminal session Ctrl+Alt+T, then create the directory structure.

[source,bash]
---------
mkdir -p ~/Projects/wsjtx-build
cd ~/Projects/wsjtx-build
----------

==== Create Build Script
*Copy & Paste* the following directly into a terminal window, and press *ENTER*

IMPORTANT: You can perform the steps manually if desired. The script merely
automates the manual tasks.

[source,bash]
----------
include::wsjtx-compile.txt[]
---------

.Change Permissions and Run Script
[source,bash]
----------
chmod +x ./wsjtx-compile.sh
./wsjtx-compile.sh
---------

==== KVASD Testing
Before you run _WSJT-X_, ensure _KVASD_ has its required libraries.

[source,bash]
-----
cd wsjtx-$rev_num
ldd ./kvasd

# If there were no missing links, test _kvasd_
./kvasd

# If successful, the K1JT copyright message will be displayed.

-----

==== Run The New WSJT-X Binary
----------
./wsjtx
----------

=== Windows CMake Example

==== Windows CMake Prerequisites

The following tools are required to compile _WSJT-X_ using _CMake_:

[horizontal]
Qt5 SDK:: The UI framework {plus} MinGW Tool Chain: {qt5_framework}
CMake:: Cross Platform Build System: {cmake}
Hamlib:: Radio Control Libraries: {hamlib}
FFTW3:: Discrete Fourier Transform library: {fftw3}
Gfortran:: Fortran compiler, included in _Qt5 SDK_
G95:: Alternate for gfortran, if desired: {g95}

