=== Linux Makefile Example

In order to build _WSJT-X_ form source, install the following packages:

----------
sudo apt-get install gcc g++ gfortran make libqt5multimedia5-plugins \
libfftw3-dev libpulse-dev libhamlib-dev qtbase5-dev qtmultimedia5-dev \
pulseaudio subversion libgfortran3:i386 libc6-i386
----------

adjust install method to you distribution package manager.

==== WSJT-X Build and Run Dependencies
[horizontal]
+gcc+:: GNU C Compiler
+g{plus}{plus}+:: GNU C{plus}{plus} Compiler
+gfortran+:: GNU Fortran or F90
+make+:: GNU Make
+libqt5multimedia5-plugins+:: QT5 Media Plugins
+libfftw3-dev+:: Fast Fourier Transforms
+libpulse-dev+:: Headers and Files for Pulse AUdio
+libhamlib-dev+:: Headers and Files for Hamlib
+qtbase5-dev+:: QT5 Base Dev Files
+qtmultimedia5-dev+:: Qt5 Multimedsia Dev Files
+pulseaudio+:: Pulse Audio Sound Driver
+subversion+:: Version Control Software
+libgfortran.so.3+:: Fortran Library
+libc.so.6+:: GCC C Library
+libm.so.6+:: GCC C Library
+libgcc_s.so.1libm.so.6+:: GCC C Library 
+libquadmath.so.0+:: Quad-Precision Math Library

==== Build Methods

All commands are performed in a terminal, Ctrl+Alt+T. Follow the
steps in the script, or perform an import to let the script do the
build.

==== Import Script
*Copy & Paste* the scipt in terminal, then enter.

IMPORTANT: You can perform the steps manually if desired. The script
simply automates the manual steps.

* Tested on Ubuntu 12.04 64-bit {amp} 14.04 64-bit
* Copy from pass:[cat > ... to ... EOL ]
* Pasting to the termainl creates a file called: wsjtx-compile.sh
* You can edit the pass:[BUILD_DIR=" .. .."] if you want different
build location.
* No other edits should be required.

[source,bash]
----
include::wsjtx-compile.txt[]
----

==== Change Permissions and Run Script
[source,bash]
-----
chmod +x ./wsjtx-compile.sh && ./wsjtx-compile.sh
-----

==== KVASD Testing

Before you launch _WSJT-X_, ensure _KVASD_ can run.

[source,bash]
---------
# cd to the newly created wsjtx-rxxxx directory then: ./kvasd -v
cd wsjtx-$rev_num
./kvasd -v

# If sucessful, you should see the version number
KVASD version 1.11

# To see the copyright information
./kvasd

---------

==== Run The New WSJT-X Binary
[source,bash]
----------
# When running from a terminal [ ./wsjtx ], the xterm remains open.
# This is good for testing and chasing errors. Run WSJT-X with:

./wsjtx

# You can also use a file manager. Browse to WSJT-X dir, and open
# as you would any other program. Using this method to launch, you
# should not see the terminal window.

----------

=== Windows CMake Example

Under Development

==== Windows CMake Prerequisites

The following tools are required to compile _WSJT-X_ using _CMake_:

[horizontal]
Qt5 SDK:: The UI framework {plus} MinGW Tool Chain: {qt5_framework}
CMake:: Cross Platform Build System: {cmake}
Hamlib:: Radio Control Libraries: {hamlib}
FFTW3:: Discrete Fourier Transform library: {fftw3}
Gfortran:: Fortran compiler, included in _Qt5 SDK_
G95:: Alternate for gfortran, if desired: {g95}

