
**_WSJT-X_** can be built on Windows, Linux and OS X. **_WSJT_** employs CMake
to manage the build process. There are many ways to build **_WSJT-X_**. This
guide will cover two primary methods:

. Build scripts for Windows, Dialog menu for Linux
. Manual entry from the command line

=== Windows
The standard method of compiling **_WSJT-X_** on Windows when using *JTSDK-QT*
is through the provided build scripts and shortcut commands.

The shell scripts provide a consistant method of build which use defaults
set in from the CMakeLists.txt file. With the exception of the Install Location,
the build script *do not* change any of the pre-set options.

If you want to customize a particular build, install location or option, you
must use the manual method described below, either with or without the aid of
CMake-GUI.

The shortcut commands provide a quick method of executing build commands without
having to type out long strings. These are similar in function to Linux Alias
Commands.

==== Compile With Scripts
Serveral targets exist for **_WSJT-X_**, both in Debug and Release. The commands
outlind below are used to checkout and build the Development Branch for types.

[[WIN32BUILDCOMMADS]]
.WSJT-X Development Branch Build Steps
[options="header,autowidth"]
|===
|Environment|Type|Command|Description

|JTSDK-QT
|Release
|
checkout-wsjtx +
build-wsjtx rconfig +
build-wsjtx rinstall +
build-wsjtx package +
build-wsjtx doc +

|
Checkout WSJT-X Development Branch from SVN +
Configure the *Release* Build Tree +
Build the *Release* Install Target +
Build the NSIS Win32 Installer +
Build the User Guide

|
|Debug
|
checkout-wsjtx +
build-wsjtx dconfig +
build-wsjtx dinstall +
build-wsjtx doc +

|
Checkout WSJT-X Development Branch from SVN +
Configure the *Debug* Build Tree +
Build the *Debug* Install Target +
Build the User Guide +

|===

.WSJT-X Special Notes
. *rconfig* and *dconfig* are used to configure the build tree, either
*Release* or *Debug*, but *do not* run the compiler. This function
can be used in conjuction with *Cmake-GUI* to enable or disable various elements
of the build.
. The *package* target exits only for the *Release* type
. The *User Guide* build has it's own Build and Install location. This is to
facilitated  working on documents without having to build the entire package.


.Commands for ( _Release and Debug_ )
=====
* Open *JTSDK-QT*, then type:
* Checkout and Configure Release Only ( no build )
-----
checkout-wsjtx
build-wsjtx rconfig
-----

* Checkout and Build Install Release Type
-----
checkout-wsjtx
build-wsjtx rinstall
-----

* Checkout and Configure Debug Only ( no build )
-----
checkout-wsjtx
build-wsjtx dconfig
-----

* Checkout and Build Install Debug Type
-----
checkout-wsjtx
build-wsjtx dinstall
-----

* Checkout and Build the User Guide
-----
checkout-wsjtx
build-wsjtx doc
-----
=====
