// Status=review
= WSJT Developer's Guide
:badges:
:icons:
:numbered:
:keywords: amateur radio weak signal communication K1JT WSJT FSK441 JT65 JT6M JT9 WSJTX
:description: Software for Amateur Radio Weak-Signal Communication

// use global link file
include::../../global/links.adoc[]

== Overview

The WSJT family of programs for weak-signal amateur radio
communication includes _WSJT_, _WSPR_, _MAP65_, _WSJT-X_, and
_WSPR-X_.  User interfaces for _WSJT_ and _WSPR_ are written in
Python, and build procedures for these two programs are similar.  User
interfaces for _MAP65_, _WSJT-X_, and _WSPR-X_ are written in C++ and
use the Qt framework, and they share most build procedures.  Most
number-crunching in all of the WSJT programs is done in Fortran.

This _Developer's Guide_ is a work in progress.  Instructions for the
Python-based programs are still to come, but we do currently provide
instructions for compiling _WSJT-X_ in Linux and we outline the
prerequisites for compiling it in Windows.  Similar procedures to these
can be used for building _MAP65_ and _WSPR-X_.

Please send feedback on this _Guide_ to {greg_beam}.

////
[[BASEENV]]
== Base Environment
include::wsjt-dev-env.adoc[]
Under Construction
////

== Source Code
include::sourcecode-dev.adoc[]

== Package Matrix
include::pkgmatrix-dev.adoc[]

////
[[DOCSETUP]]
== Documentation
include::doc-dev.adoc[]
Under Construction

[[MAP65]]
== MAP-65
include::map65-dev.adoc[]
Under Construction

[[SIMJT]]
== SIJT
include::simjt-dev.adoc[]
Under Construction

[[WSJT]]
== WSJT
include::wsjt-dev.adoc[]
Under Construction
////

[[WSJTX]]
== WSJT-X
include::wsjtx-dev.adoc[]

////
[[WSPR]]
== WSPR
include::wspr-dev.adoc[]
Under Construction

[[WSPRX]]
== WSPR-X
include::wsprx-dev.adoc[]
Under Construction
////

:numbered!:
License
-------
include::../../global/license.adoc[]
