// Status=review
= pass:[Developer's] Guide to WSJT and Related Programs
:badges:
:icons:
:numbered:
:keywords: amateur radio weak signal communication K1JT WSJT FSK441 JT65 JT6M JT9 WSJTX
:description: Software for Amateur Radio Weak-Signal Communication

// use global link file
include::../../global/links.adoc[]

== Overview

The WSJT family of programs for weak-signal amateur radio
communication includes _WSJT_, _WSPR_, _MAP65_, _WSJT-X_, and
_WSPR-X_.  User interfaces for _WSJT_ and _WSPR_ are written in
Python, and build procedures for them are similar.  User interfaces
for _MAP65_, _WSJT-X_, and _WSPR-X_ are written in C++ and use the Qt
framework.  Most number-crunching in the WSJT programs is done in
Fortran.

This pass:[Developer's] Guide is a work in progress.  We currently provide
instructions for compiling _WSJT-X_ in Linux and we outline the
prerequisites for compiling it in Windows.  Similar procedures can be
used for _MAP65_ and _WSPR-X_.  Instructions for the Python-based
programs are yet to come.

Please send feedback on this Guide to {greg_beam}.

////
[[BASEENV]]
== Base Environment
include::wsjt-dev-env.adoc[]
Under Construction
////

== Source Code
include::sourcecode-dev.adoc[]

== Package Matrix
include::pkgmatrix-dev.adoc[]

////
[[DOCSETUP]]
== Documentation
include::doc-dev.adoc[]
Under Construction

[[MAP65]]
== MAP-65
include::map65-dev.adoc[]
Under Construction

[[SIMJT]]
== SIJT
include::simjt-dev.adoc[]
Under Construction

[[WSJT]]
== WSJT
include::wsjt-dev.adoc[]
Under Construction
////

[[WSJTX]]
== WSJT-X
include::wsjtx-dev.adoc[]

////
[[WSPR]]
== WSPR
include::wspr-dev.adoc[]
Under Construction

[[WSPRX]]
== WSPR-X
include::wsprx-dev.adoc[]
Under Construction
////

:numbered!:
License
-------
include::../../global/license.adoc[]
