[[BASE_ENV]]
Before you can start developing _WSJT_ applications, you must first set up your
environment. The _{page}_ environment will use +*WSJT-ENV*+ as the containment
area for all activity. Reason(s) for this containment are:

* Establish a fixed structure to work from
* Isolate the _{page}_ examples from host system installations
* Produce repeatable results from application builds
* Create an experimental area to test installation configurations
* Minimize the installation footprint {amp} complexity v.s. Virtual Environments
* Provide a functional environment for non-developer application testing

=== Language {amp} Terms

The follwoing language is used throughout the {page}

[horizontal]
+*WSJT Env Terminal*+:: Windows CMD Terminal specifically for WSJT work 
+*Windows CMD Terminal+*:: Standard Windows Command Terminal
+*X-Term+*:: X-Terminal for Linux, BSD and OS X
+*Setup Script*+:: Batch or Shell script used to set up WSJT environment
+*Build Script*+:: Batch or Shell Script used to build applications
+*Tool Chain File*+:: CMake configuration file used by build scripts

[[PATHCFG]]
=== Path Configuration 

All _{page}_ examples use the same +*(path)*+ configuration throughout the guide:

* +*LINUX*+, all scripts and build locations will be in:
	- /home/$USER/wsjt-env <= [green]*#recommended location#*
	- /home/$USER/Projects/wsjt-env - (alternative example)
//	
* +*WINDOWS*+, all scripts, build and package installations will be in:
	- C:\wsjt-env <= [green]*#recommended location#*
	- C:\Projects\wsjt-env - (alternative example)

IMPORTANT: The {page} will use the <<PATHCFG,recommended>> install locations
for both *Windows and Linux.*	

[[WINBASESETUP]]
=== Windows Base Setup
The {page} will be using +*SlikSVN 32bit*+ as the example. If you already have
{svn} installed, ensure that it is in your %PATH% and reachable from a Windows
CMD Terminal, otherwise continue:

* Open Windows CMD Terminal, then:
----------
# CHANGE DIRVE TO
c:

# MAKE DIRECTORY - (copy & paste)
mkdir wsjt-env wsjt-env\subversion wsjt-env\downloads

# CLOSE Windows CMD Terminal and CONTINUE
----------

* Download {svn} to +*C:\wsjt-env\downloads*+
* Run the Installer
* End User Agreement: Agree to Terms
* Change Install Path to: +*C:\wsjt-env\subversion*+
* Choose Setup Type: Typical
* Finish Install
* Open Windows CMD Terminal, then:

----------
# CHECK SUBVERSION
svn --version

# IF SUCESSFUL
svn, version 1.8.5-SlikSvn-1/8/5-WIN32 .. .. ..

# CLOSE CMD and PROCEED TO APPLICATION BUILD
----------

[[LINBASESETUP]]
=== Linux Base Setup
Most Linux distributions have Subversion in their repositories. If SVN is
already installed, ensure you can use it via X-Term with: svn --version,
otherwise continue with setup:

* Open X-Term Window

----------
# DEBIAN, UBUNTU, MINT and FRIENDS
# Note: Adjust install command to your particular pkg manager
sudo apt-get install subversion

# CHECK SVN IS FUNCTIONAL
svn --version

# SUCESSFUL RETURN - Note: Versions may very slightly
svn, 1.7.14

# EXIT X-TERM and PROCEED TO APPLICATION BUILD
----------
