
All source code for the WSJT programs is available through an open-source
repository known as SourceForge, under control of the version-control
program {svn}. Subversion is included in all three development kits.
There si no need to install Subversion if you intedse to build
applications or documentation using the development kits.

You can browse the organization of files in the repository {wsjt_svn}.
Code for program _WSJT_ lies in the +trunk+ directory, while code for
the other programs is found in +.../branches/map65+,
+.../branches/wsjtx+, and +.../branches/wsprx+.  Various experimental
branches may also exist, and snapshots of code for certain released
program versions may be obtained from the +.../tags+ directory.

WARNING: Please note: the HEAD of the SVN repository for any of these
programs is likely to be an active development branch.  There is no
guarantee that a build from every revision will be successful, nor
that it will provide a stable executable program.

.CHECKOUT METHODS
There are two methods for checking out source code, <<ANONCO,Anonymous>>
and <<DEVCO,Developer>>. 

[[ANONCO]]
=== Anonymous
Anonymous checkouts allow you to build all documentation and
applications using the same methods as the developers, however,
you cannot check-in your local updates to the repository.

Each SDK has short cuts build in to simply the Anonymous checkouts.
For example, to checkout +*WSJT*+, from the JTSDK-QT environment, type:

-----
cowsjt
-----

You can also manually checkout +*WSJT*+, using
-----
svn co svn://svn.code.sf.net/p/wsjt/wsjt/trunk
-----

.Anonymous Source Code Locations:
[horizontal]
+*DOCS*+:: svn://svn.code.sf.net/p/wsjt/wsjt/branches/doc
+*WSJT*+:: svn://svn.code.sf.net/p/wsjt/wsjt/trunk
+*WSJT-X*+:: svn://svn.code.sf.net/p/wsjt/wsjt/branches/wsjtx
+*WSPR*+:: svn://svn.code.sf.net/p/wsjt/wsjt/branches/wspr
+*WSPR-X*+:: svn://svn.code.sf.net/p/wsjt/wsjt/branches/wsprx
+*MAP65*+:: svn://svn.code.sf.net/p/wsjt/wsjt/branches/map65

//

[[DEVCO]]
=== Developer
In order to use the developer checkout or checkin process

* Create a Source Force User Account
* Contact Joe Taylor, K1JT to be added to the Developer List.

Then, using +*WSJT*+ as the example:

---------
svn co svn+ssh://USER@svn.code.sf.net/p/wsjt/wsjt/trunk 
---------

Substitute your SourceForge username for +USER+.

TIP: Due to the variations in user names, developer check-out shorts 
not feasible, and must be manually entered.

.Developer Checkout Locations:

[horizontal]
+*DOCS*+:: svn{plus}ssh://USER@svn.code.sf.net/p/wsjt/wsjt/branches/doc
+*WSJT*+:: svn{plus}ssh://USER@svn.code.sf.net/p/wsjt/wsjt/trunk
+*WSJT-X*+:: svn{plus}ssh://USER@svn.code.sf.net/p/wsjt/wsjt/branches/wsjtx
+*WSPR*+:: svn{plus}ssh://USER@svn.code.sf.net/p/wsjt/wsjt/branches/wspr
+*WSPR-X*+:: svn{plus}ssh://USER@svn.code.sf.net/p/wsjt/wsjt/branches/wsprx
+*MAP65*+:: svn{plus}ssh://USER@svn.code.sf.net/p/wsjt/wsjt/branches/map65
