:prog: The WSJT Developers Guide
=== Linux Makefile

This example uses Qmake and Makefile.Linux. In order to build _WSJT-X_ form
source, install the following packages:

[[DEPS]]
[source,shell]
----------
# DEBIAN, UBUNTU, MINT and FRIENDS

# ADD QT5 PPA (Copy and Paste as "1" command in a terminal):
# This can take a while to install.
sudo add-apt-repository ppa:ubuntu-sdk-team/ppa && sudo apt-get update && \
sudo apt-get dist-upgrade && sudo apt-get install ubuntu-sdk

# AFTER QT4/5 INSTALLATION (Copy and Paste as "1" command in a terminal):
sudo apt-get install gcc g++ gfortran make libfftw3-dev \
libpulse-dev hamlib libhamlib-dev pulseaudio subversion \
libgfortran3:i386 libc6-i386 cmake

----------

==== WSJT-X Dependencies
[horizontal]
+*gcc*+:: GNU C Compiler
+*g{plus}{plus}*+:: GNU C{plus}{plus} Compiler
+*gfortran*+:: GNU Fortran or F90
+*make*+:: GNU Make
+*libqt5multimedia5-plugins*+:: QT5 Media Plugins
+*libfftw3-dev*+:: Fast Fourier Transforms
+*libpulse-dev*+:: Headers and Files for Pulse AUdio
+*libhamlib-dev*+:: Headers and Files for Hamlib
+*qtbase5-dev*+:: QT5 Base Dev Files
+*qtmultimedia5-dev*+:: Qt5 Multimedia Dev Files
+*pulseaudio*+:: Pulse Audio Sound Driver
+*subversion*+:: Version Control Software
+*libgfortran.so.3*+:: Fortran Library
+*libc.so.6*+:: GCC C Library
+*libm.so.6*+:: GCC C Library
+*libgcc_s.so.1libm.so.6*+:: GCC C Library 
+*libquadmath.so.0*+:: Quad-Precision Math Library

.Build Methods

TIP: You can perform the steps manually if desired. Using
the <<MAKEFILE,script>> is the preferred method. To perform the steps
manually, use a text editor, open the file, and follow the steps.

[[MAKEFILE]]
.Script Method
* Open a terminal, +*Ctrl{plus}Alt{plus}T*+
* Checkout +*wsjtx-makefile.sh*+ from SVN:

[source,shell]
----------
# CO BUILD SCRIPT
# use export to co a single file
# use --force to make svn update the file if it exists
svn export --force svn://svn.code.sf.net/p/wsjt/wsjt/branches/doc/dev-guide/source/wsjtx-makefile.sh

# CHANGE PERMISSION
chmod +x ./wsjtx-compile.sh

----------

.To Build Release version
[source,shell]
---------
./wsjtx-makefile.sh -r
---------

.To Build Debug version
[source,shell]
---------
./wsjtx-makefile.sh -d
---------

.WSJT-X Location
* +*/home/$USER/Projects/wsjt-env/wsjtx-$rev_num*+
* Proceed to <<CHKKVASD,check Kvasd>> then run _WSJT-X_

[source,bash]
----------
# When running from a terminal [ ./wsjtx ], the xterm remains open.
# This is good for testing and chasing errors. Run WSJT-X with:

./wsjtx

# You can also use a file manager. Browse to WSJT-X dir, and open
# as you would any other program. Using this method to launch, you
# should not see the terminal window.

----------

=== Linux CMake

This example uses CMake to build WSJT-X. The same dependencies apply. If
you have not installed the <<DEPS,dependencies>>, do so before continuing.

TIP: You can perform the steps manually if desired. Using
the <<CMAKE,script>> is the preferred method. To perform the steps
manually, use a text editor, open the file, and follow the steps.

[[CMAKE]]
.Script Method
* Open a terminal, +*Ctrl{plus}Alt{plus}T*+
* Checkout +*wsjtx-cmake.sh*+ from SVN:

[source,shell]
----------
# CO BUILD SCRIPT
# use export to co a single file
# use --force to make svn update the file if it exists
svn export --force svn://svn.code.sf.net/p/wsjt/wsjt/branches/doc/dev-guide/source/wsjtx-cmake.sh

# CHANGE PERMISSION
chmod +x ./wsjtx-cmake.sh

----------

.To Build Release version
[source,shell]
---------
./wsjtx-cmake.sh -r
---------

.To Build Debug version
[source,shell]
---------
./wsjtx-cmake.sh -d
---------

.WSJT-X Location
* +*/home/$USER/Projects/wsjt-env/wsjtx-$rev_num*+

[[CHKKVASD]]
==== Test KVASD

Before you launch _WSJT-X_, ensure _KVASD_ can run.

[source,bash]
----------
# CHANGE DIRECTORY and RUN KVASD
cd wsjtx-$rev_num
./kvasd -v

# SUCESSFUL RETURN
KVASD version 1.11

# VIEW COPYRGHT
./kvasd

----------

=== Windows CMake

This example will build _WSJT-X_ using CMake. If you have not performed the
<<BASE_ENV,Windows Base Setup>>, do so now or _WSJT-X_ build will fail.

You can build both Debuug and Release Versions with the script. If no command
line option is given, default is Release

* Open a WSJT ENV Terminal and perform the following steps:

[[SETUP]]
[source,shell]
---------
# CHANGE DIRECTORY TO INSTALL LOCATION
c:

# CD TO WSJT-ENV
cd wsjt-env

# MAKE REQUIRED DIRECTORIES
mkdir cmake fftw3f hamlib qt5 src

# CLOSE WSJT ENV Terminal
---------

==== Download Development Packages

* Save the following packages to +*C:\wsjt-env\downloads*+
* Then follow each section for installation

[horizontal]
+*Qt5 SDK*+:: {qt5_framework} - Qt 5.2.1 Windows-32, (MinGW 4.8, OpenGL)
+*CMake*+:: {cmake} - Win32 Installer
+*Hamlib*+:: {hamlib} - Hamlib 1.2.15.3.zip
+*FFTW3*+:: {fftw3} - 32-bit version: fftw-3.3.3-dll32.zip
+*MS Tools*+:: {mstools} - Microsoft Tool Kit

.QT5 Install
* Run the Installer
* Change Install Path to: +*C:\wsjt-env\Qt5*+
* Check: Associate common files types with Qt Creator
* Select Components: Use Default Selections
* License Agreement, read and select
* Start Menu: Use default selections, select next, then install
* Go grab a coffee, this takes about +*5*+ minutes to install
* At Finish, launch Qt Creator to verify it works, then exit

.CMake Install
* Run the Installer
* Agree to Terms
* Select: Do [red]*#not#* add to system PATH
* Change Install Path to: +*C:\wsjt-env\CMake*+

.Extract Hamlib
* Unzip hamlib-1.2.15.3.zip
* Copy the contents of +*hamlib-win32-1.2.15.3*+ into +*\hamlib*+. You should
end up with: +*c:\wsjt-env\hamlib\bin hamlib\lib hamlib\include ..*+

.Extract FFTW3
* [red]*#Caution#*: FFTW3 does *not* have a top level folder
* Copy +*fftw-3.3.3-dll32.zip  =>  C:\wsjt-env\fftw3f*+
* Extract in +*C:\wsjt-env\fftw3f*+ into +*c:\wsjt-env\fftw3f\*+
* Delete +*fftw-3.3.3-dll32.zip*+

[[MSTOOLS,MS Tools]]
.MS Tools - Win-XP
* Windows Vista and beyond should not need this 
* In a +*Windows CMD Terminal*+: +*c:\robocopy /?*+
* If not installed, {mstools}
* Run the installer 

.Building WSJT-X with CMake

* Check out the latest wsjt-env.bat file
* Open WIndows CMD Terminal. As this is the frst checkout, We need the Windows 
CMD Terminal, subsequent pull can be done from the WSJT Env Terminal. 

[source,shell]
----------
# CHANGE DRIVE and DIRECTORIES
c:
cd wsjt-env

# CHECK OUT LATEST WSJT-ENV FILE
svn export --force svn://svn.code.sf.net/p/wsjt/wsjt/branches/doc/dev-guide/source/wsjt-env.bat

# CHECKOUT LATEST WSJTX-BUILD-CMAKE.BAT FILE
svn export --force svn://svn.code.sf.net/p/wsjt/wsjt/branches/doc/dev-guide/source/wsjtx-build-cmake.bat

# CLOSE TERMINAL
----------

* Browse to +*C:\wsjt-env*+, Double-Click or Right-Click {amp} Open 
+*WSJT Env Terminal (wsjt-env.bat)*+.
* In the terminal, type:

IMPORTANT: When WSJT-X Build Script runs, if it cannot find one of the tools, an
error will be displayed. 

.Build Release version
[source,shell]
---------
wsjtx-build-cmake.bat -r
---------
* Location: +*C:\wsjt-env\wsjtx\wsjtx-install\Release\bin*+

.Build Debug version
[source,shell]
---------
wsjtx-build-cmake.bat -d
---------
* Location: +*C:\wsjt-env\wsjtx\wsjtx-install\Debug\bin*+
