# WSJT-X CMake Build Tool Chain File
# Part of the WSJT Documentation Project
SET (CMAKE_SYSTEM_NAME Windows)
SET (QTDIR C:/wsjt-env/Qt5/5.2.1/mingw48_32)
SET (FFTW3DIR C:/wsjt-env/fftw3f)
SET (HAMLIBDIR C:/wsjt-env/hamlib)
SET (TARGETDIR C:/wsjt-env/wsjtx-install)
SET (CMAKE_PREFIX_PATH ${QTDIR} ${FFTW3DIR} ${HAMLIBDIR} ${HAMLIBDIR}/bin)
SET (CMAKE_FIND_ROOT_PATH ${QTDIR} ${TARGETDIR})
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)