:prog: The WSJTX Developers Guide
=== Linux Makefile Example

This example uses Qmake and Makefile.Linux. In order to build _WSJT-X_ form
source, install the following packages:

[source,shell]
----------
# DEBIAN, UBUNTU, MINT and FRIENDS
# Note: Adjust the install method to your distribution package manager.

sudo apt-get install gcc g++ gfortran make libfftw3-dev \
libpulse-dev libhamlib-dev qtbase5-dev  pulseaudio subversion \
libgfortran3:i386 libc6-i386 libqt5multimedia5-plugins \
qtmultimedia5-dev

----------

==== WSJT-X Dependencies
[horizontal]
+*gcc*+:: GNU C Compiler
+*g{plus}{plus}*+:: GNU C{plus}{plus} Compiler
+*gfortran*+:: GNU Fortran or F90
+*make*+:: GNU Make
+*libqt5multimedia5-plugins*+:: QT5 Media Plugins
+*libfftw3-dev*+:: Fast Fourier Transforms
+*libpulse-dev*+:: Headers and Files for Pulse AUdio
+*libhamlib-dev*+:: Headers and Files for Hamlib
+*qtbase5-dev*+:: QT5 Base Dev Files
+*qtmultimedia5-dev*+:: Qt5 Multimedia Dev Files
+*pulseaudio*+:: Pulse Audio Sound Driver
+*subversion*+:: Version Control Software
+*libgfortran.so.3*+:: Fortran Library
+*libc.so.6*+:: GCC C Library
+*libm.so.6*+:: GCC C Library
+*libgcc_s.so.1libm.so.6*+:: GCC C Library 
+*libquadmath.so.0*+:: Quad-Precision Math Library

==== Build Methods

IMPORTANT: You can perform the steps <<MANUAL,manually>> if desired. Using the
<<BUILDSH,script>> automates the steps.

* Open a terminal session, +*Ctrl{plus}Alt{plus}T*+
* Checkout the build script from SVN:

[[BUILDSH]]
[source,shell]
.SVN export wsjtx-build.sh
----------
# SVN CHECKOUT WSJTX-COMPILE.SH
# Use Export to prevent .svn folder from downloading
# Use Force to ensure that, if wsjtx-comple.sh exists, it gets updated

svn export --force svn://svn.berlios.de/wsjt/branches/doc/dev-guide/source/wsjtx-compile.sh

----------

.Using the Script
* Using The Build <<BUILDSH,Script>>, Change Permission and Run

[source,bash]
----------
# CHANGE PERMISSION
chmod +x ./wsjtx-compile.sh

# RUN SCRIPT
./wsjtx-compile.sh
----------

[[MANUAL]]
.Manual Entry
* For manual entry, start at +*BUILD_DIR=~/Projects/wsjtx-build*+ and
perform each step that does not start with start with "#" sign. Use +*Copy {amp}
Paste*+.

[[MANUAL]]
[source,bash]
.wsjtx-compile.sh
----------
include::wsjtx-compile.sh[]
----------

==== Test KVASD

Before you launch _WSJT-X_, ensure _KVASD_ can run.

[source,bash]
----------
# CHANGE DIRECTORY and RUN KVASD
cd wsjtx-$rev_num
./kvasd -v

# SUCESSFUL RETURN
KVASD version 1.11

# VIEW COPYRGHT
./kvasd

----------

==== Run WSJT-X
Run WSJT-X from the terminal

[source,bash]
----------
# When running from a terminal [ ./wsjtx ], the xterm remains open.
# This is good for testing and chasing errors. Run WSJT-X with:

./wsjtx

# You can also use a file manager. Browse to WSJT-X dir, and open
# as you would any other program. Using this method to launch, you
# should not see the terminal window.

----------

=== Windows CMake Example

This example will build _WSJT-X_ using CMake. If you have not performed the
<<BASE_ENV,Windows Base Setup>>, do so now or _WSJT-X_ build will fail.

You can build both Debuug and Release Versions with the script. If no command
line option is given, default is Releasae

* Open a WSJT ENV Terminal and perform the following steps:

[[SETUP]]
[source,shell]
---------
# CHANGE DIRECTORY TO INSTALL LOCATION
c:

# CD TO WSJT-ENV
cd wsjt-env

# MAKE REQUIRED DIRECTORIES
mkdir cmake fftw3f hamlib qt5 src

# CLOSE WSJT ENV Terminal
---------

==== Download Development Packages

* Save the following packages to +*C:\wsjt-env\downloads*+
* Then follow each section for installation

[horizontal]
+*Qt5 SDK*+:: {qt5_framework} - Qt 5.2.1 Windows-32, (MinGW 4.8, OpenGL)
+*CMake*+:: {cmake} - Win32 Installer
+*Hamlib*+:: {hamlib} - Hamlib 1.2.15.3.zip
+*FFTW3*+:: {fftw3} - 32-bit version: fftw-3.3.3-dll32.zip
+*SVN*+:: {svn} - SlikSVN 1.8.5.x 32-bit
+*MS Tools*+:: {mstools} - Microsoft Tool Kit

.QT5.2.1 Install
* Run the Installer
* Change Install Path to: +*C:\wsjt-env\Qt5*+
* Check: Associate common files types with Qt Creator
* Select Components: Use Default Selections
* License Agreement, read and select
* Start Menu: Use default selections, select next, then install
* Go grab a coffee, this takes about +*5*+ minutes to install
* At Finish, launch Qt Creator to verify it works, then exit

.CMake Install
* Run the Installer
* Agree to Terms
* Select: Do [red]*#not#* add to system PATH
* Change Install Path to: +*C:\wsjt-env\CMake*+

.Extract Hamlib
* Unzip hamlib-1.2.15.3.zip
* Copy the contents of +*hamlib-win32-1.2.15.3*+ into +*\hamlib*+. You should
end up with: +*c:\wsjt-env\hamlib\bin hamlib\lib hamlib\include ..*+

.Extract FFTW3
* [red]*#Caution#*: FFTW3 does *not* have a top level folder
* Copy +*fftw-3.3.3-dll32.zip  =>  C:\wsjt-env\fftw3f*+
* Extract in +*C:\wsjt-env\fftw3f*+ into +*c:\wsjt-env\fftw3f\*+
* Delete +*fftw-3.3.3-dll32.zip*+

[[MSTOOLS,MS Tools]]
.MS Tools - Win-XP
* Windows Vista and beyond should not need this 
* In a +*Windows CMD Terminal*+: +*c:\robocopy /?*+
* If not installed, {mstools}
* Run the installer 

==== Building WSJT-X with CMake

* Browse to +*C:\wsjt-env*+, Double-Click or Right-Click {amp} Open 
+*WSJT Env Terminal (wsjt-env.bat)*+.
* In the terminal, type:

IMPORTANT: When WSJT-X Build Script runs, if if cannot find one of the tools, an
error will be displayed. 

.Build Release version
[source,shell]
---------
wsjtx-build-cmake.bat -r
---------
* Location: +*C:\wsjt-env\wsjtx\wsjtx-install\Release\bin*+

.Build Debug version
[source,shell]
---------
wsjtx-build-cmake.bat -d
---------
* Location: +*C:\wsjt-env\wsjtx\wsjtx-install\Debug\bin*+
